### ISSUE TITLE
PICCOLO_CONF environment variable clarification

### ISSUE THREAD

**Issue by kremrik** [piccolo-orm/piccolo#102]
I'm working on a project where I want to maintain a directory structure like
```
api
├── db
│   ├── __init__.py
│   ├── piccolo_conf.py
```
Since my `piccolo_conf.py` file is no longer at the root of the project, I need to specify the `PICCOLO_CONF` environment variable. For the sake of clarity (and I'm happy to make a PR for this), is it valuable to add an example to the [docs](https://github.com/piccolo-orm/piccolo/blob/master/docs/src/piccolo/engines/index.rst) highlighting that the required format for the path looks like this:
```api.db.piccolo_conf```
rather than this?
```api/db/piccolo_conf.py```
I kept running into errors the when using the latter format, but the former is accepted.

**Comment by dantownsend** [comment]
Hi @kremrik - you make a good point. I think it's worth adding this to the docs. If you're happy to prepare a MR for it, that would be great. Thanks!

**Comment by kremrik** [comment]
You know what, it took me a few dozen passes over the documentation but I finally saw this hint in the docs. Not sure how I missed it for so long, but I don't think this requires any changes. Feel free to close!
![piccolo_hint_screenshot](https://user-images.githubusercontent.com/34952189/118883582-03f95880-b8bb-11eb-94d0-4ed7e7d066a9.png)

**Comment by dantownsend** [comment]
I missed that too. The hint box probably isn't the best place for this.
