### ISSUE TITLE
Replace deprecated `startup` and `shutdown` events in asgi templates 

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo#1026]
Replace the deprecated `startup` and `shutdown` events in Starlette and FastAPI asgi templates with `lifespan` events. The working [branch is here](https://github.com/piccolo-orm/piccolo/compare/master...sinisaos:piccolo:lifespan_events).

**Comment by dantownsend** [comment]
I've noticed this deprecation warning, but wasn't sure how to fix it. I had a look at your branch, and it looks good to me, if you want to create a PR. Thanks!
