### ISSUE TITLE
Unable to import Max, Sum in piccolo[postgres]==0.113.*

### ISSUE THREAD

**Issue by sarvesh-deserve** [piccolo-orm/piccolo#1042]
This is the error that I am getting. 
ModuleNotFoundError: No module named 'piccolo.query.functions'

**Comment by sinisaos** [comment]
Sorry both if I'm wrong but in piccolo version `0.113.*` aggregate functions was in different module (`piccolo/query/select.py`). Best way is to upgrade Piccolo to version `>=1.6.0`. Than we can use aggregate functions like this
```python
from piccolo.query.functions.aggregate import Max, Sum
```

**Comment by dantownsend** [comment]
I re-exported `Count` from `select.py` to try and keep backwards compatibility:

https://github.com/piccolo-orm/piccolo/blob/ce250611adf6b0a1df7d03ca4bd8fecf698e83c1/piccolo/query/methods/select.py#L39

But it looks like I made a mistaken by not re-exporting `Avg`, `Max`, `Min` and `Sum`. So you're right, it would be a breaking change.

We should probably re-export these from `select.py`.

**Comment by dantownsend** [comment]
This should be fixed in `piccolo==1.13.1`. Thanks both.
