### ISSUE TITLE
Object.refresh() mutates relations

### ISSUE THREAD

**Issue by trondhindenes** [piccolo-orm/piccolo#1056]
If an object is retrieved with relations then refreshed, the relation switches from the "related object" to an int representing the relation id:

```
crawler = await Crawler.objects(Crawler.crawler_status).get(Crawler.identifier == identifier)
```
crawler.crawler_status now contains the full related object

```
crawler.refresh()
```
crawler.crawler_status now contains an int pointing to the related object, instead of the full object.

**Comment by dantownsend** [comment]
Yes, good point - this needs fixing. It should be possible.

**Comment by sinisaos** [comment]
I don't know if this makes sense because that's one db query more, but for now we can use [get_related](https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_types/objects.html#get-related) to get the full object instead of the relation id after a `refresh()` like this
```python
crawler = await Crawler.objects(Crawler.crawler_status).get(Crawler.identifier == identifier)
crawler.refresh()
await crawler.get_related(Crawler.crawler_status)
```

**Comment by dantownsend** [comment]
Yeah, using `get_related` is an option.

I can imagine the current behaviour catching people out.

What we could do is look at the object being refreshed, and see if any of the attributes are also objects. If so, update those child objects too.

I did a quick prototype locally, and I think we can make it work.

**Comment by dantownsend** [comment]
I put a PR up which fixes this, but there's a limitation at the moment.

It's possible to prefetch objects multiple layers deep:

```python

**Comment by dantownsend** [comment]
OK, I managed to make it work multiple levels deep. Just need to write some more tests.

**Comment by dantownsend** [comment]
This was fixed by https://github.com/piccolo-orm/piccolo/pull/1058 and will be in the next release.

Thanks!

**Comment by trondhindenes** [comment]
nice, thanks for the quick response and fix - as always!
