### ISSUE TITLE
Incomplete "Get the tests running" documentation

### ISSUE THREAD

**Issue by haaavk** [piccolo-orm/piccolo#1061]
If you follow step by step instructions from [documentation](https://piccolo-orm.readthedocs.io/en/latest/piccolo/contributing/index.html#get-the-tests-running) running tests fail. 
There are errors:
- for postgres: `ModuleNotFoundError: PostgreSQL driver not found. Try running pip install 'piccolo[postgres]'`
- for sqlite: `ModuleNotFoundError: SQLite driver not found. Try running pip install 'piccolo[sqlite]'`

Installing piccolo[postgres] or piccolo[sqlite] is probably not good solution in this context. 
I guess running `pip install requirements/extras/postgres.txt` and `pip install requirements/extras/sqlite.txt` is proper solution. 
This step should be somehow included in documentation.

**Comment by sinisaos** [comment]
@dantownsend Sorry to interrupt, but wouldn't it be much simpler to add `aiosqlite` and `asyncpg` to `requirements/test-requirements.txt` since those dependencies are used to test the Piccolo library itself. With that, we do not have to change the documentation.

**Comment by dantownsend** [comment]
@sinisaos There's an argument for adding them to `test-requirements.txt` or even `dev-requirements.txt`.

If using that approach, I think we can add this to the end of `test-requirements.txt`:

```
-r extras/postgres.txt
-r extras/sqlite.txt
```

The pros of this is it's one less thing for a dev to type when getting setup (i.e. `pip install -r requirements/extras/postgres.txt`).

The downside is with our CI - this is what it currently does when getting setup:

https://github.com/piccolo-orm/piccolo/blob/bb37027d2982ebb7ff69e37ca83c5a3fd1708707/.github/workflows/tests.yaml#L154-L157

If `test-requirements.txt` has the dependencies for both sqlite and postgres, it means it's slightly wasteful - i.e. we will install asyncpg in the sqlite tests. Our CI currently has about 20 different combinations of Python and database versions, and it might grow in the future.

**Comment by sinisaos** [comment]
@dantownsend Thank you for the explanation. My mistake, I forgot about CI and cons by adding those dependencies directly to `test-requirements.txt`. Sorry.

**Comment by haaavk** [comment]
Ok. I'll make a PR.

**Comment by dantownsend** [comment]
@sinisaos No worries, it was a good idea.

@haaavk Thanks!
