### ISSUE TITLE
Allow using uuid instead of integer for the id column

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo#107]
Right now piccolo admin returns a weird ID when uuid is used as a primary key

![4C6CC5B0-40D8-4AF6-804C-F1B6567D39F7](https://user-images.githubusercontent.com/66250972/120886158-294fcb80-c60a-11eb-9d10-64b7b3b3de1b.png)

**Comment by dantownsend** [comment]
I haven't tried this before - I tend to use integers as the primary key.

I'll give it a go, to try and understand what's going on.

**Comment by cheesycod** [comment]
@dantownsend it appears to try and make the uuid a integer which somehow succeeds

**Comment by aminalaee** [comment]
@cheesycod Do you have this issue with `sqlite`?
