### ISSUE TITLE
programmatic/dynamic where clause

### ISSUE THREAD

**Issue by trondhindenes** [piccolo-orm/piccolo#1072]
Hi, 
I'm working on a problem atm that I feel might not be documented:
Given a query like this:

```
crawler_definitions = await (
        CrawlerDefinition.objects(CrawlerDefinition.crawler)
        .offset(paging_data.get_offset())
        .limit(paging_data.page_size)
        .order_by(paging_data.page_sort_field, ascending=paging_data.get_asc())
        .where(CrawlerDefinition.crawler.identifier == uuid.UUID(identifier))
    )
```    
if the user supplies a boolean `active_only` we want to add an extra where clause. 
I'm struggling to find the right syntax for it, it doesn't seem to be documented. I've tried something like:

```
    if active_only:
        active_only_query = CrawlerDefinition.is_active.eq(True)
    else:
        active_only_query = None
    crawler_definitions = await (
        CrawlerDefinition.objects(CrawlerDefinition.crawler)
        .offset(paging_data.get_offset())
        .limit(paging_data.page_size)
        .order_by(paging_data.page_sort_field, ascending=paging_data.get_asc())
        .where(CrawlerDefinition.crawler.identifier == uuid.UUID(identifier)).where(active_only_query)
    )
```
My problem is that I don't know what to put in the "else" block to represent "don't worry about this at all"
 
It would be cool if it was possible to do something like (pseudocode) - maybe it already is
```
query = CrawlerDefinition.crawler.identifier == uuid.UUID(identifier)
query = query + <new query> 
```
but I dont see an api to "append" an extra where clause.

It would be good if there was a better documented query builder that could be used for this kind of dynamic queries. Or maybe there already is one, but I had problems figuring it out from the docs :thinking:

**Comment by dantownsend** [comment]
Oh yeah, you're right - this doesn't seem to be documented.

It's a pretty easy solution, which I use all of the time.

Basically something like:

```python
query = (
        CrawlerDefinition.objects(CrawlerDefinition.crawler)
        .offset(paging_data.get_offset())
        .limit(paging_data.page_size)
        .order_by(paging_data.page_sort_field, ascending=paging_data.get_asc())
        .where(CrawlerDefinition.crawler.identifier == uuid.UUID(identifier))
    )

if active_only:
    query = query.where(CrawlerDefinition.is_active.eq(True))

crawler_definitions = await query
```

Does that solve the problem?

**Comment by trondhindenes** [comment]
Thanks! So that chains the existing where clause with the new so that it becomes an 'And'?

**Comment by dantownsend** [comment]
Yes, that's right.

**Comment by trondhindenes** [comment]
that works! Thanks a lot!

**Comment by dantownsend** [comment]
No problem - will try and update the docs to mention this.
