### ISSUE TITLE
ASGI template doesn't work for Esmerald 3.4.1

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#1078]
I noticed our integration tests fail when using `esmerald==3.4.1`.

However, if I version pin to `esmerald==3.3.0` they still work (I picked this older version arbitrarily).

https://github.com/piccolo-orm/piccolo/actions/runs/10863888957/job/30148554519?pr=1077

**Comment by dantownsend** [comment]
@sinisaos and @tarsil Any ideas?

**Comment by tarsil** [comment]
Let me have a look. We didn't change anything core in this version

**Comment by sinisaos** [comment]
@dantownsend The latest version of `esmerald` that passes the integration test is `3.3.7` but if we make a new project with `piccolo asgi new` (in fresh env) everything works with newest version `3.4.1`. I have no idea what is causing this behavior.

**Comment by dantownsend** [comment]
Thanks both, what a weird mystery.

As @sinisaos says, if we install 3.4.1 outside of the integration tests, it works OK.

The integration tests work by having a very basic ASGI server, which runs the app and makes sure a 200 is returned.

https://github.com/piccolo-orm/piccolo/blob/2f8e84cad3a337a7738b726cf6bacf8bc11dfff1/tests/apps/asgi/commands/files/dummy_server.py#L25-L30

In this case we get a 500 back instead of a 200, which fails the tests.

This is the scope we send to the ASGI app:

https://github.com/piccolo-orm/piccolo/blob/2f8e84cad3a337a7738b726cf6bacf8bc11dfff1/tests/apps/asgi/commands/files/dummy_server.py#L35-L43

I wonder if Esmerald expects something different in the scope in this version?

**Comment by sinisaos** [comment]
@tarsil I tried to go a little deeper and if I create new asgi app with `piccolo asgi new` but replace `uvicorn` with `dummy_server` in `main.py` (`debug` mode) I get this traceback error starting with `esmerald>3.3.7`

<details>
<summary>Error traceback</summary>

```bash
Running dummy server ...
Traceback (most recent call last):
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/middleware/asyncexitstack.py", line 38, in __call__
    await self.app(scope, receive, send)
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/lilya/routing.py", line 1590, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/lilya/routing.py", line 1430, in app
    await self.handle_route(route, path_handler=path_handler)
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/lilya/routing.py", line 1333, in handle_route
    await route.handle_dispatch(path_handler.scope, path_handler.receive, path_handler.send)  # type: ignore
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/routing/gateways.py", line 348, in handle_dispatch
    await self.app(scope, receive, send)
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/routing/router.py", line 2038, in __call__
    await self.handle_dispatch(scope=scope, receive=receive, send=send)
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/routing/router.py", line 2130, in handle_dispatch
    response = await self.get_response_for_request(
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/routing/base.py", line 505, in get_response_for_request
    response = await self.call_handler_function(
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/routing/base.py", line 532, in call_handler_function
    response_data = await self._get_response_data(
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/routing/base.py", line 205, in _get_response_data
    request_data = await parameter_model.get_request_data(request=request)
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/transformers/model.py", line 175, in get_request_data
    return await request.json()
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/esmerald/requests.py", line 65, in json
    body = self.scope["_body"] = await self.body() or b"null"
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/lilya/requests.py", line 181, in body
    self._body = b"".join([chunk async for chunk in self.stream()])  # type: ignore
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/lilya/requests.py", line 181, in <listcomp>
    self._body = b"".join([chunk async for chunk in self.stream()])  # type: ignore
  File "/home/rkl/dev/esmerald_env/lib/python3.10/site-packages/lilya/requests.py", line 157, in stream
    if event["type"] == Event.HTTP_REQUEST:
TypeError: 'NoneType' object is not subscriptable
200 not received from app
```
</details>

I'm not familiar with Esmerald and Lilya internals but if I add check if event is not None with something like this
```python
# in lilya/request.py
async def stream(self) -> AsyncGenerator[bytes, None]:
    """
    Stream the request body in asynchronous chunks.

    Yields:
        AsyncGenerator[bytes, None]: Bytes representing chunks of the request body.
    """
    if self._body is Empty:
        if self._stream_consumed:
            raise RuntimeError("Stream consumed")
        event = await self._receive()
        if event is not None: # check event
            while not self._stream_consumed:
                if event["type"] == Event.HTTP_REQUEST:
                    if not event.get("more_body", False):
                        self._stream_consumed = True
                    if event["body"]:
                        yield event["body"]

                elif event["type"] == Event.HTTP_DISCONNECT:
                    self._is_disconnected = True
                    raise ClientDisconnect()
        yield b""

    else:
        yield cast(bytes, self._body)
        yield b""
        return

```
, `dummy_server` is work and status code is `200`. I don't know if that breaks something else, but can you check that? Thanks.

**Comment by tarsil** [comment]
I will have a look at this. We haven't updated Lilya in a while so it might be something else. Quick question, if the version is the 3.4.0, does it work as expected? Because if it does, I might know what the problem might be and I can address that tomorrow

**Comment by tarsil** [comment]
@sinisaos the reason why I'm saying that it's because piccolo also supports Lilya and we don't have that problem with it

**Comment by sinisaos** [comment]
> I will have a look at this. We haven't updated Lilya in a while so it might be something else. Quick question, if the version is the 3.4.0, does it work as expected? Because if it does, I might know what the problem might be and I can address that tomorrow

The latest working version is `3.3.7`. Both `3.4.0` and `3.4.1` do not work and the error from the previous comment raised.

> @sinisaos the reason why I'm saying that it's because piccolo also supports Lilya and we don't have that problem with it

Yes that strange, everything should be work because, if I'm not wrong, `Esmerald` is built on the top of `Lilya`.

**Comment by sinisaos** [comment]
> I wonder if Esmerald expects something different in the scope in this version?

@dantownsend Yes. You were right. After trying a simple Esmerald application with uvicorn, I see in that app `request.scope` has an argument `"_body": b"null"` which is different from the `dummy_server` scope. We need to add the argument `"_body": b"null"` to the `dummy_server` scope, then the integration test passed with Esmerald 3.4.1. It's not a new feature of Esmerald, but it's kind of needed now in integration tests. If you want I can do a PR for it.

**Comment by tarsil** [comment]
> > I wonder if Esmerald expects something different in the scope in this version?
> 
> @dantownsend Yes. You were right. After trying a simple Esmerald application with uvicorn, I see in that app `request.scope` has an argument `"_body": b"null"` which is different from the `dummy_server` scope. We need to add the argument `"_body": b"null"` to the `dummy_server` scope, then the integration test passed with Esmerald 3.4.1. It's not a new feature of Esmerald, but it's kind of needed now in integration tests. If you want I can do a PR for it.

That is great that you actually manage to find that. I was struggling to understand the issue 😕

**Comment by dantownsend** [comment]
@sinisaos OK, cool - glad we go to the bottom of it.

I wonder what `_body` does? I found a reference to a `more_body` parameter in ASGI.

Either way though, if it works, then great. A PR would be much appreciated.

**Comment by sinisaos** [comment]
It was not easy to find that little thing, but it was strange to me that everything works with `uvicorn` (and not with `dummy_server`) and then I went to see what the difference is in `request.scope`. That was the only thing that differs between the `uvicorn` scope and the `dummy_server`.

**Comment by dantownsend** [comment]
It makes sense that a body would be sent with an ASGI request. I wonder why it's `_body` and not `body`? Ah well, it's a mystery.

Good detective skills.

**Comment by tarsil** [comment]
I will have a look as that doesn't make any sense. Esmerald since ever had it but it's an attribute of the request. Same as Lilya and Lilya didn't have that issue

**Comment by dantownsend** [comment]
I'll close this now then.

To give a quick summary of the problem / solution:

* We have an integration test for Esmerald, where we install an app in an empty virtualenv, and then run the app with a really simple ASGI server to make sure we get a 200 response.
* For some reason it started failing.
* @sinisaos looked into it,  and we could only get the test running by adding `_body` to the ASGI scope - but it's kind of weird, because `_body` isn't part of the ASGI spec, and is something Lilya/Esmerald uses internally.
* So we decided to just replace our ASGI server with the `TestClient` from `httpx`, which doesn't have this problem.

So yeah, still a bit of a mystery, but we have a solution now.

Thanks both 👍

**Comment by tarsil** [comment]
> I'll close this now then.
> 
> To give a quick summary of the problem / solution:
> 
> * We have an integration test for Esmerald, where we install an app in an empty virtualenv, and then run the app with a really simple ASGI server to make sure we get a 200 response.
> * For some reason it started failing.
> * @sinisaos looked into it,  and we could only get the test running by adding `_body` to the ASGI scope - but it's kind of weird, because `_body` isn't part of the ASGI spec, and is something Lilya/Esmerald uses internally.
> * So we decided to just replace our ASGI server with the `TestClient` from `httpx`, which doesn't have this problem.
> 
> So yeah, still a bit of a mystery, but we have a solution now.
> 
> Thanks both 👍

Thank you both but reading the summary I understood one thing. The TestClient was changed and now everything works. That would explain a lot. Starlette/Lilya did some refactoring for that to make sure some properties were ignore with the new uvicorn, specifically. 

I have no words to describe how much we as community appreciate your time to fix it. Everyone loves piccolo and seeing you all working to make sure nothing fails warms our hearts. On behalf of the Dymmond community, thank you.

**Comment by sinisaos** [comment]
@tarsil Thank you for your kind words.
