### ISSUE TITLE
Is it possible to execute a raw query in batch mode, similar to how we do it for select queries?

### ISSUE THREAD

**Issue by devsarvesh92** [piccolo-orm/piccolo#1079]

**Comment by dantownsend** [comment]
We don't expose a `batch` method in ``raw`` queries - we probably should though. It would be pretty easy to add.

You can work around it though like this though:

```python
async with await SomeTable._meta.db.batch(SomeTable.raw("SELECT * FROM my_table")) as batch:
    async for _batch in batch:
        print(_batch)
```

**Comment by sarvesh-deserve** [comment]
Thanks @dantownsend

**Comment by sarvesh-deserve** [comment]
@dantownsend is there a sync version?

**Comment by dantownsend** [comment]
I've added batch to raw queries now - it'll be in a future release.
