### ISSUE TITLE
How about Form_generator?

### ISSUE THREAD

**Issue by Anonymous1313-tech** [piccolo-orm/piccolo#108]
How about form generator for piccolo models? I think it would be awesome if there was function something like greate_form(piccolo_table)!

**Comment by dantownsend** [comment]
The best option currently is to use Piccolo Admin. I know you're having issues with it on Windows, but it's worth trying to get it running.

There's no support for anything like [WTForms](https://wtforms.readthedocs.io/en/2.3.x/) at the moment.

Piccolo API has a function called `create_pydantic_model` ([see docs](https://piccolo-api.readthedocs.io/en/latest/crud/serializers.html?highlight=pydantic#create-pydantic-model)). This is one way to automatically create a serialiser from a Piccolo `Table`.
