### ISSUE TITLE
Objects accept node parameter for choosing extra node

### ISSUE THREAD

**Issue by erhuabushuo** [piccolo-orm/piccolo#1099]
Objects accept node parameter for choosing extra node

**Comment by sinisaos** [comment]
@erhuabushuo Sorry if I missed your point, but the [run](https://github.com/piccolo-orm/piccolo/blob/f4bf25a133dd6a0f28c95571ee97bf75be87befe/piccolo/query/base.py#L141-L143) method (usually the `run` method is optional, but in this case you must explicitly use the `run` method with `objects` or `select` queries) has a `node argument` to pass another [Postgres database node](https://piccolo-orm.readthedocs.io/en/latest/piccolo/engines/postgres_engine.html#piccolo.engine.postgres.PostgresEngine). Something like this
```python
await MyTable.objects().run(node="your_node")
# or
await MyTable.select().run(node="your_node")
```
Hope that helps.

**Comment by erhuabushuo** [comment]
Thanks for your help!
