### ISSUE TITLE
SQLite table creation works without async/await but fails with it

### ISSUE THREAD

**Issue by ketannabera** [piccolo-orm/piccolo#1129]
### Description
When using Piccolo with SQLite in-memory database, table creation fails when using async/await but works without it.

### Environment
- Python version: 3.12
- Piccolo version: 1.17.*
- FastAPI version: 0.114.*
- Database: SQLite (in-memory)

```python
### Code that fails
@app.on_event("startup")
async def create_tables():
    await Users.create_table(if_not_exists=True)
    
    Error: sqlite3.OperationalError: no such table: users
    
### Code that works
@app.on_event("startup")
def create_tables():
    Users.create_table(if_not_exists=True)
    

### Full minimal reproduction
# piccolo_conf.py
from piccolo.engine.sqlite import SQLiteEngine
DB = SQLiteEngine(path=":memory:")

# models.py
from piccolo.columns import UUID, Varchar
from piccolo.table import Table

class Users(Table):
    user_id: UUID = UUID(null=False)
    name: Varchar = Varchar()

# application.py
from fastapi import FastAPI
app = FastAPI()

@app.on_event("startup")
def create_tables():  # works without async/await
    Users.create_table(if_not_exists=True)
  
  ```
### Expected Behavior :
According to documentation, Piccolo is async-first and all database operations should work with async/await.

### Question :
Why does table creation work without async/await but fail with it when using SQLite in-memory database?

**Comment by dantownsend** [comment]
With this:

```python
Users.create_table(if_not_exists=True)
```

The options are either run it async:

```python
await Users.create_table(if_not_exists=True)
```

Or run it sync:

```python
Users.create_table(if_not_exists=True).run_sync()
```

Note the `run_sync` at the end, which is required.

In an ideal world, `run_sync` wouldn't be required, but this doesn't work with how async is implemented in Python.

When using Piccolo I recommend using async 99% of the time, and using sync just when needed - it's just a better experience.

**Comment by ketannabera** [comment]
Hey @dantownsend . I agree with the explanation and I was initially using async itself. 
But it kept failing for me while using Sqlite in-memory database.
For added context, I am actually running a FastAPI + piccolo + Sqlite(in-memory) application on my local. 

Do you have any idea as to why it would fail for this combination ?

**Comment by sinisaos** [comment]
@ketannabera This has already been discussed [here](https://github.com/piccolo-orm/piccolo/discussions/1032). If you pass `:memory:?cache=shared` to engine like this
```python
DB = SQLiteEngine(path=":memory:?cache=shared")
```
you can create a table with async. But it will create a file `:memory:?cache=shared`, so it's the same as using `SQLiteEngine `with nothing in the constructor (which creates a default `piccolo.sqlite` file). Here is the working code.

```python
# from contextlib import asynccontextmanager
from fastapi import FastAPI
from piccolo.columns import UUID, Varchar
from piccolo.table import Table

from piccolo.engine.sqlite import SQLiteEngine

# # or simply this to create the default `piccolo.sqlite`
# DB = SQLiteEngine() 
DB = SQLiteEngine(path=":memory:?cache=shared") # <- this is change


class Users(Table, db=DB):
    user_id: UUID = UUID(null=False)
    name: Varchar = Varchar()


# # or with lifespan
# @asynccontextmanager
# async def lifespan(app: FastAPI):
#     await Users.create_table(if_not_exists=True)
#     yield


# app = FastAPI(lifespan=lifespan)
app = FastAPI()


@app.on_event("startup")
async def create_tables():
    await Users.create_table(if_not_exists=True)
```
I hope this helps

**Comment by ketannabera** [comment]
@sinisaos thanks for sharing this. It worked ! :)
