### ISSUE TITLE
session_login trying to fetch login.html template for GET method

### ISSUE THREAD

**Issue by heliumbrain** [piccolo-orm/piccolo#115]
I have the login endpoint mounted in my FastAPI like so:

```python
from piccolo_api.session_auth.endpoints import session_login
from piccolo_api.session_auth.tables import SessionsBase
from piccolo.apps.user.tables import BaseUser

app = FastAPI()

app.mount(
    path="/login/",
    app=session_login(
        auth_table=BaseUser,
        session_table=SessionsBase,
        redirect_to=None,
        production=False,
        cookie_name="session"
    ),
)
```

Doing a GET request to /login/ throws a `TemplateNotFound` error

```
jinja2.exceptions.TemplateNotFound: login.html
```

Full trace here: https://sentry.io/share/issue/2149cf3dcfce4585846ad47d672495e8/

I'm guessing this endpoint was designed to be used together with the Admin app and `create_admin()`, where the template is available?

Might be good to add a check that returns a `Method not allowed` if a template doesn't exist.

Thoughts?

**Comment by sinisaos** [comment]
@heliumbrain A quick fix is ​​to add a template folder (with login.html inside from [here](https://github.com/piccolo-orm/piccolo_api/blob/master/piccolo_api/session_auth/templates/login.html)) to your virtualenv site package (for example `/yourhomefolder/nameofvirtualenv/lib/python3.8/site-packages/piccolo_api/session_auth`). You can then go to /login/ and sign in user and redirect to any page you want. Daniel will probably know a better solution, but this may be a temporary solution.

**Comment by dantownsend** [comment]
@sinisaos Good suggestion.

Turns out the setup.py for piccolo_api had an issue, and wasn't including the template file. I've been caught out by this a few times.

https://github.com/piccolo-orm/piccolo_api/pull/44

Will push a new version for PyPI soon.

**Comment by heliumbrain** [comment]
Thanks @dantownsend. It's working as expected now :)
