### ISSUE TITLE
[Question] Is there a capability to connect to multiple databases

### ISSUE THREAD

**Issue by dashsatish** [piccolo-orm/piccolo#142]
Django provides a capability to define `DATABASE_ROUTERS` in settings.
- It gives you a capability to define alias names in `DATABASES` for primary, replica*(1,2,3... so on).
- you can customize the connection to read from replicas whereas write only to primary.
- `QuerySet` object also provides assistance for this setting.
https://docs.djangoproject.com/en/3.2/topics/db/multi-db/

Is there such a definition in piccolo to connect to multiple instances (or databases) and accordingly read and write queries  can be split for efficiency? Did not find anything in the docs.

**Comment by dantownsend** [comment]
@dashsatish The support for this is quite simplistic at the moment in Piccolo.

You can explicitly pass an `Engine` instance to a `Table` subclass, and it will use that for its queries. For example:

```python
# This will just use the `Engine` assigned to the `DB` variable in piccolo_conf.py
class TableA(Table):
    name = Varchar()

alternative_db = PostgresEngine({database: 'db_2'})

# This will use `alternative_db` for all of it's queries instead.
class TableB(Table, db=alternative_db)
    name = Varchar()
```

There isn't currently a way to dynamically switch between databases on a per query basis. For example something like this:

```python
await MyTable.select().run(db_name="db_2")
```
It would mean that `DB` in `piccolo_conf.py` would have to support dictionaries:

```python
DB = {
    'default': PostgresEngine({'database': 'db_1'),
    'db_2': PostgresEngine({'database': 'db_2')
}
```

Things like this would then be possible:

```python
class TableB(table, db=engine_finder(name="db_2")):
    name = Varchar()
```

It gets a bit tricky with migrations, as each migration would need to know which database to run on.

I'll have a look at how Django does it. If you have any ideas let me know.

**Comment by satishdash** [comment]
Django allows few class definitions(they call it routers) like db_for_read, write, allow_migrate. This facilities migrations or sets privileged operations on such instances. 
If the ORM can support such a thing like you have described above it would be really great. Hope you glanced through the django docs that i have mentioned above. Is it feasible?

**Comment by dashsatish** [comment]
@dantownsend Did you have a look at ^^. Believe to be a good feature to have, where one can use specific engine objects while querying a table.

**Comment by dantownsend** [comment]
@dashsatish I was thinking about this the other day.

I do think it's a good idea. Just need to work out what the API would look like. As you mention, Django has routers which determine what to use for read / write etc. That's one option.

Another option which would fit quite easily into Piccolo is:

```python
await MyTable.select().run(using='read_only')
```

At the moment, Piccolo expects `DB` in `piccolo_conf.py` to be a single `Engine` instance.   It could also be something like this:

```python
DB = EngineRouter(
    engines={
        'default:' PostgresEngine(...),
        'read_only:' PostgresEngine(...),
   }
)
```

OR, it might be easier if `Engine` can have children.

```python
DB = PostgresEngine(
    config={
         'database:' 'my_database'
    },
    # I'm not sure if 'alternatives' is the best name ... needs thinking about:
    alternatives={
         'read_only': PostgresEngine(config={'database': 'my_read_only_database'})
    }
)
```

What do you think?

**Comment by dantownsend** [comment]
I've implemented a first version - will release it now. There's future scope for adding routers etc like in Django, but hopefully this helps.

**Comment by dashsatish** [comment]
@dantownsend This is an awesome start ! 🙂. The one with the `EngineRouter` seems more API user-friendly. Perhaps we can get to that in the future versions? Hopefully the backward compatibility can still be maintained.

**Comment by dantownsend** [comment]
@satishdash Yeah, we can definitely build on top of it.

Something like this perhaps:

```python
DB = PostgresEngine(
    config={...},
    extra_nodes={
        'read_slave_1': PostgresEngine(config={...})
    },
    routing={
        'get': {'some_table': 'read_slave_1'}
    }
)
```

Once an API design has been settled on, it shouldn't be too hard to implement. If you have any ideas for an API let me know.

**Comment by dantownsend** [comment]
@renanmoretto That's a good point - I've never tried that. I don't think it will work at the moment. The migrations assume the tables all belong to the main database.

You can work around it by excluding that table from the migrations (in your `piccolo_app.py` file), and then creating the other table in the other database manually using `Usage.create_table().run_sync()` or `await Usage.create_table()`.

**Comment by renanmoretto** [comment]
@dantownsend 
gotcha, thanks!

so there is no way to easily manage migrations/db with multiple databases, right? gotta do it manually

is there something similar to django db routers in piccolo?

**Comment by renanmoretto** [comment]
got it, thanks for the replies!
