### ISSUE TITLE
Configuring event loop implementation

### ISSUE THREAD

**Issue by aminalaee** [piccolo-orm/piccolo#143]
As far as I know there's no way to set up any event loop other than Python's `asyncio`. And to my understanding if using `uvloop` performance will be improved.

I suggest we add `uvloop` as an extra dependency and maybe do one of the followings:
- Try using `uvloop` as default and if not available fallback to `asyncio`
- Pass the event loop to the engine confugarion
Or any other ways you can suggest.

**Comment by dantownsend** [comment]
@aminalaee Yeah, it's an interesting one. If running Piccolo as part of an ASGI app with Uvicorn, then Uvicorn will automatically set uvloop as the event loop implementation if it's installed:

https://www.uvicorn.org/settings/#implementation

If using Piccolo as part of a data science script, or synchronous web app, it would currently be up to the user to manually configure uvloop.

```python
# At the top of their main Python file.
import uvloop
uvloop.install()
```

Piccolo could have uvloop as an optional import.

```
pip install piccolo[uvloop]
```

And when calling the Piccolo CLI via `piccolo/main.py` could setup uvloop if it's installed. What do you think?

**Comment by aminalaee** [comment]
That makes sense. I'll add it in.
