### ISSUE TITLE
Support direct .__await__

### ISSUE THREAD

**Issue by uwinx** [piccolo-orm/piccolo#15]
Hey there, seems like a nice library. It's just a small suggestion and opinion, but you can add `__await__` for the queries, instead of kind of an annoying `.run` every time

```python3
class Q:
    async def _actual_call(self) -> T:
        # .... do_some_work .... '
        return 

    def __await__(self) -> Generator[None, None, T]:
        return self._actual_call().__await__()

q = Q()
await q
```

Suggestion related to `picollo/query/base::Query`

**Comment by dantownsend** [comment]
@uwinx That's a great suggestion - thanks. The original design intention for Piccolo was to make it as explicit as possible when database queries were actually being made. Some existing ORMs do database queries when accessing properties etc, which can lead to performance issues. But I have to admit, the explicit `.run()` can be a pain, and I sometimes forget it.

And as you're calling `await` on the query, it's still explicit that you're expecting it to do something.

I've created a pull request for the change. I'll mull it over tonight, in case there's some edge case I haven't considered.

**Comment by sinisaos** [comment]
@uwinx Maybe is annoying and sometimes I forget to call `.run()` but I like explicit way to run query because I know exactly what need to do. And like docs say's - "Until you execute one of those methods, you can chain as many methods onto your query as you like, safe in the knowledge that no database queries are being made." I look at that like advantage.

**Comment by dantownsend** [comment]
@sinisaos Yeah, there are pros and cons to each approach.

The chaining of methods will still work, with or without the explicit `.run()`:

```python
await MyTable.select().first().run() 
await MyTable.select().first()
``` 

I'm thinking of merging the changes in, and having it as a convenience. What do you think?

The question then becomes - would you do the same thing for the synchronous version. You could set the `__call__` method for `Query`, and then do this:

```python
MyTable.select()()
# Equivalent to:
MyTable.select().run_sync()
```

It looks a bit weird though.

**Comment by sinisaos** [comment]
@dantownsend Async way looks good and there is good convenience while the functionality stays the same. But Piccolo provide both Async and Sync support and you're right about the Sync way looks weird.

Personally, I like the explicit `.run()` and `.run_sync()`.

**Comment by dantownsend** [comment]
@sinisaos I'll keep `.run()` as the default way of doing things in the docs. It makes it slightly more future proof, as `run()` can accept arguments - currently it's just whether or not to run the query in a connection pool, which is mostly used for testing purposes, but there may be other arguments which need to be added in the future. The `__await__` magic method can be there as a convenience, for people who prefer the more compact syntax. I won't add the `__call__` magic method for now - it's just too weird.

**Comment by uwinx** [comment]
@dantownsend, off-topic:
where can I reach you (any social media telegram/discord/etc.)? I'm interested in contributing to project

**Comment by dantownsend** [comment]
@uwinx Of course, that would be great. I’m quite old school, so email is the most reliable way to contact me - dan at dantownsend.co.uk

I’m @pypower on Discord. I’m open to other suggestions in terms of best platforms to collaborate with.

**Comment by dantownsend** [comment]
@sinisaos I've setup a Discord server for talking about Piccolo development. Most discussion will still happen here on Github, but if you're a Discord user and would like me to add you, let me know :)

**Comment by sinisaos** [comment]
@dantownsend I'm not a Discord user and I don't use any social media :). You may want to consider using [Gitter](https://gitter.im/) chat  because you only need a Github account to create a community and then just add a chat link to Piccolo website.

**Comment by dantownsend** [comment]
@sinisaos Good suggestion - I'll take a look.
