### ISSUE TITLE
Is there a way to use all columns of a joined table?

### ISSUE THREAD

**Issue by brnosouza** [piccolo-orm/piccolo#160]
I was working in a feature and I had to list all the columns of a related table, is there a better way to select all columns without having to list all? Something like the `star` method in peewee.

**Comment by dantownsend** [comment]
Using the example schema in the docs:

```python
class Manager(Table):
    id = Serial()
    name = Varchar()

class Band(Table):
    id = Serial()
    name = Varchar()
    manager = ForeignKey(references=Manager)
    popularity = Integer()
```

You can try something like:

```python
# To get the band name, and all manager columns
Band.select(
    Band.name,
    *[getattr(Band.manager, column._meta.name) for column in Manager._meta.columns]
).run_sync()
```

There could definitely be a nicer API for it - like you mention, something like:

```python
Band.select(
    Band.name,
    Band.manager.star
).run_sync()
```

I'll try and add this at some point.
