### ISSUE TITLE
Insert & get

### ISSUE THREAD

**Issue by adriangb** [piccolo-orm/piccolo#171]
Is there any way to do an INSERT and subsequent SELECT of the inserted object w/o a second SELECT query? It look like INSERT returns the PK, but there's no way to add additional columns, change the cardinality, etc.

**Comment by adriangb** [comment]
Indeed, `RETURNING` is hardcoded: https://github.com/piccolo-orm/piccolo/blob/14e7c72634a8614edec87e8cbbd8eb2101d84f93/piccolo/query/methods/insert.py#L64

**Comment by dantownsend** [comment]
You're right - this is a good idea. I'll have a think about how to tackle this.
