### ISSUE TITLE
Automigrations fails for models using ForeignKey

### ISSUE THREAD

**Issue by hipertracker** [piccolo-orm/piccolo#178]
I can't run migrations with `--auto` flag when a model uses a `ForeignKey`.
```
class Book(Table, tablename="books"):
    name = Varchar(length=32, unique=True)
    label = JSON(default=dict())
    sort = Integer(default=0, index=True)
    available = Boolean(default=True, index=True)
    tags = Array(base_column=Varchar(length=32), default=[])

class BookAlias(Table, tablename="book_aliases"):
    name = Varchar(length=32)
    book = ForeignKey(references="Book")
```
piccolo migrations new home --auto
Running Postgres version 13.4
Creating new migration ...
The command failed.
**unhashable type: 'list'**

**Comment by hipertracker** [comment]
It's not related to the Postgres version. I tested it also on the supported Postgres 11.1 with the same effect

```
$ piccolo migrations new home --auto
Running Postgres version 11.1
Creating new migration ...
The command failed.
unhashable type: 'list'
```

**Comment by dantownsend** [comment]
@hipertracker It will be related to the default argument on `tags` - seems like an edge case which isn't caught by the unit tests. I'll take a look at this.
