### ISSUE TITLE
Case insensitive value matching

### ISSUE THREAD

**Issue by wmshort** [piccolo-orm/piccolo#191]
Loving Piccolo ORM. But is it possible to match a column value case-insensitively _without_ also being constrained by wildcard patterns, using .ilike() (which requires a wildcard pattern with '%'? It seems it would be beneficial to be able to match column values indifferently to case, but to exclude 'start', 'end' or 'within' patterns. For example: .where(Table.column == 'value') would match both 'Value' and 'value', but not values such as 'some value' (%value) or 'Value too!' (value%) or 'devalued' (%value%), as required by .ilike(). Or am I missing something?

**Comment by dantownsend** [comment]
@wmshort Hi William.

You make a good point - this should be possible.

It's a quick fix, I just need to remove the validation, so it doesn't complain if there's no % in the query.

That way you can just do:

```python
await MyTable.select().where(MyTable.column.ilike('foo')).run()
```

**Comment by dantownsend** [comment]
Until I get this fix out, here's a work around:

```python
await MyTable.select().where(MyTable.column.is_in(['foo', 'Foo'])).run()
```

**Comment by wmshort** [comment]
Hi Dan, that's great! Thanks for the quick response and promised quick fix. (I suspect it was just this sort of issue on Piccolo's end, rather than something in the interface with SQL). I had thought of something like 'is_in' as well, but this is only sometimes the right solution, since with certain data it's impossible to predict beforehand what the variations might be (e.g. it could be Foo or FOO or foO or fOo or whatever, and you might want to match them all, but still not 'Foobar' or 'foobar' or ... you get the picture).

Thanks again!
