### ISSUE TITLE
Get dict from ORM objects?

### ISSUE THREAD

**Issue by wmshort** [piccolo-orm/piccolo#200]
Is it possible to get a dict of column names and values easily from ORM objects, as if you had originally done .select()? I mean, once you have some ORM objects, I'm finding I then sometimes want to treat these objects purely in terms of their values. I guess there is the brutish .__dict__, but that wouldn't offer the filtering or aliasing opportunities of .select(). I guess I am asking if it's possible to .select() from the result of a Table.objects() query.

**Comment by dantownsend** [comment]
I agree, having a separate `to_dict` method would be better than overriding `__dict__`.

**Comment by dantownsend** [comment]
@wmshort There's an open PR which adds the fix.

Let me know if this is what you expected, if so I'll release it later today.

**Comment by wmshort** [comment]
That's brill, yes! I haven't tested it yet, is it possible to provide columns for inclusion, as well as aliasing? I had imagined something like this:

```
object.to_dict()       # all model columns, except of course the internal ones
object.to_dict(Table.column_name)    # include only the user specified column
object.to_dict(Table.column_name.as_alias('column_alias'))    # alias the specified column name
```

Or mix and match
``
object.to_dict(Table.column1_name, Table.column2_name.as_alias('column_alias'))
# include column1 and column2 (but not, say, column3) and simultaneously alias column2, leaving column1 as-is
```

**Comment by dantownsend** [comment]
@wmshort Cool, makes sense - I can see that being useful. Have updated the PR.
