### ISSUE TITLE
specifying multiply-nested fields in select?

### ISSUE THREAD

**Issue by wmshort** [piccolo-orm/piccolo#209]
Loving the new nested functionality. It works wonders! But I'm running into an issue with ``select()`` and ``all_columns()`` when I have multiply-nested models. So, imagine:

```
class Day:
     name: str
     order_in_week: int

class Place:
     name: str

class Hobby:
     name: str
     day_for_doing: Day
     place_for_doing: Place

class Person:
     hobby: Hobby
     name: str
     other_field: str
```

The trouble I am running into -- and this may just be a question of not having the syntax of ``select()`` right -- is that I get a "missing FROM-clause for table 'hobby'" error when trying to do something like: 

``Person.select(Person.other_field, *Person.hobby.day.all_columns(), *Person.hobby.place.all_columns()).where(Person.name ==  'Bob').run()`` 

It appears to be an issue with referencing the intermediate model (here, Hobby); but how else can I specify all_columns() on the doubly-nested table? If I just do ``*Person.hobby.all_columns()``, I get a Pydantic validation error saying that (in this example) ``day_for_doing`` and ``place_for_doing`` are not valid dicts.

Does ``all_columns()`` also need a ``nested`` option? Or am I missing something about how to specify columns in ``select()``?

**Comment by dantownsend** [comment]
The syntax you're using looks correct. I'll try it locally to see if I can replicate the problem.

**Comment by wmshort** [comment]
I've tried both:
``Person.hobby.day.all_columns()`` = 'missing FROM-clause entry for table hobby' error
``Person.hobby.all_columns()`` = Pydantic validation error, as nested models in Hobby are not valid ``dict``s

I used ``create_pydantic_models(nested=True...)`` for all the nested tables, omitting ``nested`` only from the models lowest in the hierarchy (i.e. Day, Place in the example) which do not themselves have anything nested. This is working nicely, as in the FastAPI Swagger UI, a correctly nested schema is displayed for the relevant endpoint!

**Comment by dantownsend** [comment]
I've been able to replicate the issue. 

The problem is if `all_columns` is used two or more levels deep:

```python
Person.select(*Person.hobby.place_for_doing.all_columns()).run_sync()
>>> error
```

I'll try and fix it.

It's a bit tedious, but for now if you list all of the columns explicitly it seems to work OK (just as a temporary fix).

```python
Person.select(
    Person.name,
    Person.hobby.place_for_doing.name,
    Person.hobby.day_for_doing.name,
    Person.hobby.day_for_doing.order_in_week
).output(nested=True).run_sync()
```

**Comment by wmshort** [comment]
Alrighty, I will try the explicit method for now! Thanks!
