### ISSUE TITLE
Naming of columns

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#221]
### Discussed in https://github.com/piccolo-orm/piccolo/discussions/206

Allow ``Table`` columns to map to database columns with different names.

For example:

```python
class MyTable(Table):
    name = Varchar(name="person_name")
```

In the example above, when doing queries, you will use `MyTable.name`, but the actual column in the database is called `person_name`.

This is useful when using Piccolo on legacy databases with non-ideal column names.

**Comment by gmos** [comment]
Would be nice to have this.  I have an existing database with a column name called 'class'.  So named the field 'class_' in the definition.  But then obviously table accesses fail.  So needed a workaround.

Already wanted to make a view in the database to change the offending name.  But then looked into the code and found this workaround:
```
class LoraKey(Table, tablename="copy_lora_key", db=DB):
    # ...
    class_ = Varchar(null=False, length=1, alias="class")

LoraKey.class_._meta._name = 'class'
```
Seems to do the job nicely, albeit a bit of a hack.

**Comment by gmos** [comment]
> 
> Seems to do the job nicely, albeit a bit of a hack.

Alas, while fetching and updating works, creating and initializing a new instance doesn't. 
```
t1 = LoraKey( class_="A", other=42 )  # doesn't find the field and vs-code gives a warning
t2 = LoraKey( class="A", other=42 )   # obviously gives a syntax error.
# Need to do it in steps for this to work...
t3 = LoraKey( other=42 )
t3['class'] = "A"
```

**Comment by dantownsend** [comment]
@gmos I had a quick go at fixing this issue - still need to write some more tests, but hopefully should be able to release it soon.

**Comment by dantownsend** [comment]
The most problematic thing is passing it into the constructor - so in your example `LoraKey( class="A", other=42 )`.

There's a related issue, where a dictionary of arguments can be passed in. This is one potential fix:

https://github.com/piccolo-orm/piccolo/issues/268

I think it's cleaner than letting a user pass in either `class` or `class_`. I'll have a think.

**Comment by dantownsend** [comment]
@gmos There's a new version on PyPI which supports this feature now. Hopefully it solves your issue.

This should now work:

```python
class LoraKey(Table, tablename="copy_lora_key", db=DB):
    class_ = Varchar(null=False, length=1, db_column_name='class')
```

**Comment by dantownsend** [comment]
There's also this approach for anyone coming across this in the future:

https://github.com/piccolo-orm/piccolo/blob/69389132d5946ea29f98a763d015afe49fbc5b86/piccolo/table.py#L955

So it's:

```python
from piccolo.table import create_table_class

LoraKey = create_table_class(
    class_kwargs={'tablename': 'copy_lora_key', 'db': DB},
    class_members={'class': Varchar(null=False, length=1)}
)
```

A bit harder to read, but useful in a pinch.

**Comment by gmos** [comment]
Just installed the new version.  Works perfectly.  Thnx.
