### ISSUE TITLE
Is there support for columns that take enums as type (like postgres has!)

### ISSUE THREAD

**Issue by satishdash** [piccolo-orm/piccolo#23]
Is there a support for enum types in piccolo? or an approach to achieve it like `DjangoMixin`. This just an enquiry didn't have a forum to ask for help hence posting it here.

Thanks! Awesome work btw.

**Comment by satishdash** [comment]
In addition, I'm starting to use piccolo over Sqlalchemy because alembic is great but it misses few migrations.

**Comment by dashsatish** [comment]
Any thoughts on this?

> Is there a support for enum types in piccolo? or an approach to achieve it like `DjangoMixin`. This just an enquiry didn't have a forum to ask for help hence posting it here.
> 
> Thanks! Awesome work btw.

**Comment by sinisaos** [comment]
@dashsatish I don't think that for now Piccolo have that feature but probably Daniel know better. Maybe is easiest workaround is to use reference table and pass FK to table you need. Piccolo has nice [Readable](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/advanced.html#readable) feature to present nice dropdown in Piccolo admin. Sorry if I miss your point.

**Comment by dantownsend** [comment]
@satishdash Thanks for your interest in the project. As @sinisaos says, Piccolo doesn't currently support enums unfortunately. The best way to handle it for now is a foreign key to a separate table, or to handle the validation in your app somehow.

I don't think it would be too hard to add for Postgres, so I'll put it on the roadmap.

**Comment by dashsatish** [comment]
> @satishdash Thanks for your interest in the project. As @sinisaos says, Piccolo doesn't currently support enums unfortunately. The best way to handle it for now is a foreign key to a separate table, or to handle the validation in your app somehow.
> 
> I don't think it would be too hard to add for Postgres, so I'll put it on the roadmap.

Exactly! just wanting to know your thoughts on this on how to handle it. And yes since postgres is the most used RDMS DB store, it'd be a good add. But thanks for the suggestions anyways.

**Comment by dashsatish** [comment]
Please go ahead and close this!

**Comment by MoSheikh** [comment]
Would actually love to see this for Postgres - anywhere you could point me towards towards helping out with this?

**Comment by sinisaos** [comment]
@MoSheikh I know it's not the same thing, but you could try using a Python `Enum` with the [Choices](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/advanced.html#choices) option. This option is more flexible because Python enums are not fixed and can be changed as you like without migrations or anything. I apologize if that is not a satisfactory answer.
