### ISSUE TITLE
Fix bug with Decimal / Numeric columns

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#232]
There's a subtle bug where if you have a `Decimal` / `Numeric` column, and don't specify a `digits` argument.

https://github.com/piccolo-orm/piccolo/blob/23a8c1f8cedee518288ecb702454f62521583c13/piccolo/columns/column_types.py#L908

For example:

```python
class MyTable(Table):
    # In this case Postgres just allows the maximum digits the database will support:
    value = Numeric()
```

The problem is when using `create_pydantic_model` it assumes the `precision` and `scale` properties of `Numeric` / `Decimal` return an integer - but they raise an exception.

https://github.com/piccolo-orm/piccolo/blob/23a8c1f8cedee518288ecb702454f62521583c13/piccolo/utils/pydantic.py#L120-L123

We just need to return something sensible from `precision` and `scale` if `digits` isn't set.

And if they're not available, we should use a standard decimal field in Pydantic rather than `pydantic.condecimal`.

**Comment by AliSayyah** [comment]
@dantownsend pydantic's default value for max_digits and decimal_places is None, so if we return None when precision and scale are not defined, it should be okay. 

> And if they're not available, we should use a standard decimal field in Pydantic rather than pydantic.condecimal.

so is it necessary to use another field in this case?

**Comment by dantownsend** [comment]
@AliSayyah That makes sense - just have `max_digits` and `decimal_places` set to `None`

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo/pull/236
