### ISSUE TITLE
Add `create_tables` function

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#233]
If you want to create a table without using migrations, you can do this:

```python
Band.create_table().run_sync()
```

If you're creating a bunch of tables, you need to do something like:

```python
Manager.create_table().run_sync()
Band.create_table().run_sync()
```

You have to be careful to create them in the right order because of `ForeignKey` columns.

We have a useful utility which can automatically sort tables based on their foreign keys so they're created in the right order.

https://github.com/piccolo-orm/piccolo/blob/23a8c1f8cedee518288ecb702454f62521583c13/piccolo/apps/migrations/auto/migration_manager.py#L165

So we can quite easily create a ``create_tables`` function in tables.py, which accepts a list of tables, passes them to `sort_table_classes`, and then creates each of them in turn.

```python
create_tables(Band, Manager, if_not_exists=True)
```

We will be able to use this to cut out boilerplate from our tests, and will also be useful for people writing simple data science scripts using Piccolo, who don't need migrations.

**Comment by AliSayyah** [comment]
This sounds very useful. I'll get onto it.

**Comment by AliSayyah** [comment]
@dantownsend I'm not sure what the function should return. do you have any idea?

**Comment by dantownsend** [comment]
@AliSayyah I think it's fine not to return anything - if something goes wrong, an exception will be raised anyway.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo/pull/235
