### ISSUE TITLE
Suppressed error stack when the command code fails

### ISSUE THREAD

**Issue by hipertracker** [piccolo-orm/piccolo#249]
When Piccolo runs a command and the code raises an error, it's hard to figure out what's wrong because the output displays only a simple message. It would be a great help to add a full error stack to the output.

**Comment by dantownsend** [comment]
@hipertracker Try the command with --trace`, and it should output a stack trace.

You need to make sure you have the latest version of `targ` installed for this to work.

I don't think this is mentioned in the docs - it needs adding.

**Comment by hipertracker** [comment]
I added information about --trace flag https://github.com/piccolo-orm/piccolo/pull/254
