### ISSUE TITLE
[BUG]: Decimal import conflict in auto generated migration

### ISSUE THREAD

**Issue by 0scarB** [piccolo-orm/piccolo#306]
Auto-generating migrations for tables with columns of type `Decimal` causes conflicting imports <br>
```python
from piccolo.columns.column_types import Decimal
```
and 
```python
from decimal import Decimal
```
<br>

This means that the following code in the migration fails
```python
manager.add_column(
        ...
        column_class_name="Decimal",
        column_class=Decimal,  # Wrong `Decimal` - is `decimal.Decimal`, should be `piccolo.columns.column_types.Decimal`!!!
        params={
            "default": Decimal("0"),  # Correct `Decimal` - is `decimal.Decimal`
            "digits": None,
            "null": False,
            "primary_key": False,
            "unique": False,
            "index": False,
            "index_method": IndexMethod.btree,
            "choices": None,
            "db_column_name": None,
        },
    )
```

because `Decimal` has type `decimal.Decimal`, not `piccolo.columns.column_types.Decimal`. <br><br>

This probably hasn't been discovered yet because most people use `Numeric` which does not have this problem.

## Quick Fix
Use an absolute import or import alias in generation.

## Extensive Fix
Although this certainly is an edge case, similar import conflicts may occur in the future. To future-proof new code one could, for example, check for conflicts during generation and fall back on absolute imports.

**Pro:** Future-proof
**Con:** Extra code-complexity

---
**piccolo version** == 0.57.0

## Full example
**broken_decimal/tables.py**
```python
from piccolo.table import Table
from piccolo.columns import Decimal, Numeric


class BrokenDecimalAutoMigration(Table):
    # This breaks migration auto generation because of `Decimal` import conflict.
    dec_col = Decimal()

    # This works
    # dec_col = Numeric()
```
<br>

`piccolo migrations new broken_decimal --auto` generates **broken_decimal/piccolo_migrations/2021-10-15T19-10-02-685456.py**
```python
from piccolo.apps.migrations.auto import MigrationManager
from decimal import Decimal
from piccolo.columns.column_types import Decimal
from piccolo.columns.indexes import IndexMethod


ID = "2021-10-15T19:10:02:685456"
VERSION = "0.57.0"
DESCRIPTION = ""


async def forwards():
    manager = MigrationManager(
        migration_id=ID, app_name="broken_decimal", description=DESCRIPTION
    )

    manager.add_table(
        "BrokenDecimalAutoMigration", tablename="broken_decimal_auto_migration"
    )

    manager.add_column(
        table_class_name="BrokenDecimalAutoMigration",
        tablename="broken_decimal_auto_migration",
        column_name="dec_col",
        db_column_name="dec_col",
        column_class_name="Decimal",
        column_class=Decimal,
        params={
            "default": Decimal("0"),
            "digits": None,
            "null": False,
            "primary_key": False,
            "unique": False,
            "index": False,
            "index_method": IndexMethod.btree,
            "choices": None,
            "db_column_name": None,
        },
    )

    return manager
```
<br>

`piccolo migrations forwards broken_decimal` fails with error message `The digits argument should be a tuple.`

**Comment by dantownsend** [comment]
@0scarB Yeah, the `ast` approach sounds interesting.

I only have limited experience with the `ast` module, so even though it sounds good conceptually, I'm not sure how complex it would be in practice.

This seems like a good resource on it:

https://greentreesnakes.readthedocs.io/en/latest/index.html

Feel free to create a new issue and build a prototype if you like.
