### ISSUE TITLE
Improve tests for `piccolo asgi new`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#317]
We have a basic test for `piccolo asgi new`:

https://github.com/piccolo-orm/piccolo/blob/master/tests/apps/asgi/commands/test_new.py

It can definitely be improved though. As a minimum, we should read the generated file contents, and use `ast.parse(file_contents)` to make sure the file is valid Python code. We use a similar approach here:

https://github.com/piccolo-orm/piccolo/blob/e0f04a40e868e9fa3c4f6bb9ebb1128f74180b07/tests/apps/schema/commands/test_generate.py#L91

Even better, we would try and run the app to make sure it works, but this might be too tricky.

**Comment by AliSayyah** [comment]
@dantownsend That seems like a fun challenge. I would like to work on this.

**Comment by dantownsend** [comment]
@AliSayyah Thanks, much appreciated. Even if it's just using `ast.parse` it will be a big improvement.

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo/pull/340
