### ISSUE TITLE
Fix the docs

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#318]
Looks like docutils version needs to be pinned.

https://github.com/sphinx-doc/sphinx/issues/9727

**Comment by AliSayyah** [comment]
It seems that we are ok.
Sphinx 4.2.0 has a `docutils < 18` pin.

**Comment by yezz123** [comment]
@dantownsend I was asking why not use Mkdocs, its have a lot of good UI and style to use for a futuristic documentation 🤔

**Comment by dantownsend** [comment]
@AliSayyah Thanks, I'll try re-running it, and hopefully it'll work.

@yezz123 I considered MKDocs in the past. Markdown is generally more pleasant to work with than RST, and the [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) theme is great.

I have a love/hate relationship with Sphinx. It can be tricky to use. But the thing I really like is how it can auto generate docs from your code, like in the attached image.

I've been looking for a better theme for Sphinx, one of these might do:

 * https://github.com/pradyunsg/furo
 * https://github.com/bashtage/sphinx-material/

<img width="735" alt="Screenshot 2021-11-01 at 14 51 36" src="https://user-images.githubusercontent.com/350976/139691294-9fda067c-dbf5-4767-ad7e-4a641d09d12e.png">

**Comment by dantownsend** [comment]
The issue is fixed now. I created a separate discussion for themes:

https://github.com/piccolo-orm/piccolo/discussions/320
