### ISSUE TITLE
piccolo cli can't find piccolo_conf when app is run as a module from outside the module directory

### ISSUE THREAD

**Issue by theelderbeever** [piccolo-orm/piccolo#323]
I typically structure my apps so that they can use relative imports and as a consequence will run my application from outside the app directory. When using `piccolo` this requires me to update some of the module locations and registrations but I can get the application run with `uvicorn --host 0.0.0.0 --port 8000 --reload app.app:app` just fine. However, when I attempt to use the `piccolo migrations check` command it is unable to import the `APP_REGISTRY` because it can't find the `piccolo_conf` file. `cd`-ing to the app directory does not resolve the issue.

Directory structure
```console
.
├── app
│   ├── __init__.py
│   ├── app.py
│   ├── home
│   │   ├── __init__.py
│   │   ├── endpoints.py
│   │   ├── migrations
│   │   │   └── README.md
│   │   ├── piccolo_app.py
│   │   └── templates
│   │       ├── base.html.jinja
│   │       └── home.html.jinja
│   ├── models
│   │   ├── __init__.py
│   │   └── events.py
│   ├── piccolo_conf.py
│   ├── routes
│   │   ├── __init__.py
│   │   └── events.py
│   └── static
│       ├── favicon.ico
│       └── main.css
└── tests
    └── test_app.py
```

By running from just above the app dir I can structure imports as `from .models.events import Event` for example.
My `app.py` is shown below. Note the import structure and that the static directory mount was updated as well as the `engine_finder` to point at the correct conf. Unfortunately, this does not seem to extend to the configuration of the `piccolo` cli. 

```python
# app.py

import os

from aiocache import caches
from fastapi import FastAPI
from piccolo.engine import engine_finder
from piccolo_admin.endpoints import create_admin
from starlette.routing import Mount, Route
from starlette.staticfiles import StaticFiles

from .home.endpoints import HomeEndpoint
from .home.piccolo_app import APP_CONFIG
from .routes import events

caches.set_config(
    {
        "default": {
            "cache": "aiocache.SimpleMemoryCache",
            "serializer": {"class": "aiocache.serializers.StringSerializer"},
        },
        "redis": {
            "cache": "aiocache.RedisCache",
            "endpoint": os.environ["REDIS_HOST"],
            "port": int(os.environ["REDIS_PORT"]),
            "serializer": {"class": "aiocache.serializers.PickleSerializer"},
            "plugins": [
                {"class": "aiocache.plugins.HitMissRatioPlugin"},
                {"class": "aiocache.plugins.TimingPlugin"},
            ],
        },
    }
)

app = FastAPI(
    routes=[
        Route("/", HomeEndpoint),
        Mount(
            "/admin/",
            create_admin(
                tables=APP_CONFIG.table_classes,
                # Required when running under HTTPS:
                # allowed_hosts=['my_site.com']
            ),
        ),
        Mount("/static/", StaticFiles(directory="app/static")),
    ],
)

app.include_router(events.router)


@app.on_event("startup")
async def open_database_connection_pool():
    try:
        engine = engine_finder(module_name="app.piccolo_conf")
        await engine.start_connection_pool()
    except Exception:
        print("Unable to connect to the database")


@app.on_event("shutdown")
async def close_database_connection_pool():
    try:
        engine = engine_finder(module_name="app.piccolo_conf")
        await engine.close_connection_pool()
    except Exception:
        print("Unable to connect to the database")
```

Attempting to run migrations. Note that the app directory resides in `/`.
```console
> default@f9e8c16aeb01:/$ piccolo migrations check
Can't import the APP_REGISTRY from piccolo_conf - some commands may be missing. If this is a new project don't worry. To see a full traceback use `piccolo --diagnose`
Listing migrations ...
APP NAME             | MIGRATION_ID               | DESCRIPTION                              | RAN
The command failed.
No module named 'piccolo_conf'
```
Running the cli from inside `/app` complains about `attempted relative import with no known parent package`. Is there a way for the cli to support relative imports or running outside the app directory?

**Comment by theelderbeever** [comment]
Explicitly adding the application directory to your `PYTHONPATH` seems to work but this doesn't seem like a great methodology.

**Comment by dantownsend** [comment]
Hi @theelderbeever, thanks for reporting this issue.

One solution might be to use the `PICCOLO_CONF` environment variable ([more info](https://piccolo-orm.readthedocs.io/en/latest/piccolo/engines/index.html#piccolo-conf-environment-variable)). Something like:

```
export PICCOLO_CONF=app.piccolo_conf
```

That way you should be able to use the Piccolo CLI from the root directory.

I tend to run the Piccolo CLI from the same folder as the `piccolo_conf.py` file, so haven't encountered this issue before, but will have a play around.

I hope that helps.

**Comment by theelderbeever** [comment]
Thanks! `PICCOLO_CONF` appears to be solving the issue from what I can tell right now. I was hoping this would be the case because I much prefer `piccolo` to the other orms!

**Comment by dantownsend** [comment]
@theelderbeever Cool, glad that seems to work. Thanks for the kind words.

If there are any other issues, let me know.
