### ISSUE TITLE
suggestion: add a refresh_object method and updated_fields param

### ISSUE THREAD

**Issue by trondhindenes** [piccolo-orm/piccolo#338]
use case: If I'm dealing with the same record in multiple methods, they may overwrite eachother:

```
async def stuff1(email):
   customer = await Customer.objects().where(Customer == email).first()
   await stuff2(email)
   customer.good = True
   await customer.save()

async def stuff2(email):
   customer = await Customer.objects().where(Customer == email).first()
   customer.some_other_stuff = True
   await customer.save()
```
in this case, `some_other_stuff` will be overwritten, because `stuff1` will write it's entire object state to the db. 

Two things that would help here:
1. being able to call `await customer.refresh_db()` to get an up-to-date view of the object
2. being able to call `await customer.save(update_fields=['good']) to avoid overwriting other attributes which the current function has no interest in

**Comment by dantownsend** [comment]
@trondhindenes Yeah, this is a tricky thing with ORMs - when the objects become out of sync with what's in the database.

One solution for now is to use ``update``:

```python
await Customer.update({Customer.good: True}).where(Customer.email == 'test@foo.com')
```

But in terms of making it work better with `save`, I guess there are a few options:

 1. Automatically tracking which values have changed, and only syncing those values back.
 1. Provide an extra argument to the `save` method where you can specify what to sync back to the database.
 1. The `refresh_db` option could work too.
