### ISSUE TITLE
Pylance complains about import in auto generated migrations.

### ISSUE THREAD

**Issue by gmos** [piccolo-orm/piccolo#356]
![image](https://user-images.githubusercontent.com/1526544/142867514-9294c787-8fb7-4e23-a4cb-f0be7b52b0af.png)

Dan,

As the screenshot shows Pylance seems to ignore the relative import of the MigrationManager done in `piccolo/apps/migrations/auto/__init__.py` and wants to see:
`from piccolo.apps.migrations.auto.migration_manager import MigrationManager`
 
I'll also check Pylance's issue list.  Think it should use exactly the same import sematics as Python itself.
Nevertheless, this would be easy to fix by adjusting the generated import in Piccolo's auto migration code generator.

**Comment by dantownsend** [comment]
@gmos That's an odd one. I'll change the import in the next release, thanks.

**Comment by dantownsend** [comment]
@gmos Thanks for looking into it so thoroughly. I've done a PR for option 2 - using a more explicit import path.

Importing it as `__MigrationManager` is a clever solution, which would fix the issue for existing migration files. Hopefully there's an official solution in the future in Python or Pyright.
