### ISSUE TITLE
piccolo migrations new my_app doesn't create new blank migration

### ISSUE THREAD

**Issue by theelderbeever** [piccolo-orm/piccolo#418]
`piccolo migrations new my_app` doesn't create a new migration if there are no table changes since the last migration. This makes it difficult to create `raw` migrations.

```console
❯ piccolo migrations new my_app
Creating new migration ...
Created tables                           0
Dropped tables                           0
Renamed tables                           0
Created table columns                    0
Dropped columns                          0
Columns added to existing tables         0
Renamed columns                          0
Altered columns                          0
No changes detected - exiting.
```

**Comment by dantownsend** [comment]
@theelderbeever Yeah, that's odd. When you use `piccolo migration new my_app` without the `--auto` flag, it should just create a blank migration.

It must be some kind of edge case. Is this a brand new app?

**Comment by theelderbeever** [comment]
Nah its an older app but I have been bumping the version.

Also I can't repro it this morning so I have no idea. I can reopen if I can repro it later.

**Comment by theelderbeever** [comment]
Okay I think I repro'd it... It fails when you include the `--desc` option however, it will succeed when removing that.
```console
❯ piccolo migrations new my_app --desc "some message"
Creating new migration ...
Created tables                           0
Dropped tables                           0
Renamed tables                           0
Created table columns                    0
Dropped columns                          0
Columns added to existing tables         0
Renamed columns                          0
Altered columns                          0
No changes detected - exiting.
```

**Comment by dantownsend** [comment]
@theelderbeever Yes, you're right - how strange! I'll take a look.

**Comment by dantownsend** [comment]
It turns out it's a limitation of the targ library which powers Piccolo's CLI. 

It needs an equals sign:

```
piccolo migrations new my_app --desc="some message"
```

I'll try and fix it

https://github.com/piccolo-orm/targ/blob/694ab94e6578eaf6f63c86d74e6d2b0c4da0de6d/targ/__init__.py#L356

**Comment by sinisaos** [comment]
@dantownsend I think you can close this because it's done.

**Comment by dantownsend** [comment]
I've opened an issue in the targ library so track the outstanding work.

https://github.com/piccolo-orm/targ/issues/16
