### ISSUE TITLE
syntax error when adding index in migration

### ISSUE THREAD

**Issue by wmshort** [piccolo-orm/piccolo#431]
I am trying to add an index to a Varchar column on a table. Auto creating migrations work perfectly fine, but when I try to run the migration it fails with a syntax error ('syntax error at or near' + name of column). This is the only change in the migration and the migration file itself does not contain errors. Any sense for what could be causing the issue?

Thanks

**Comment by dantownsend** [comment]
@wmshort What column type was it? And what's the column name? I'll try and recreate the issue.

I just tried this simple example, and it seemed OK:

```python
class Task(Table):
    name = Varchar(index=True)
```

I didn't explicitly specify an index method - I used the default one, which is btree.

There could be some kind of edge case.
