### ISSUE TITLE
Document how to run code on a table's records during migration

### ISSUE THREAD

**Issue by trondhindenes** [piccolo-orm/piccolo#441]
Today I found myself adding a new boolean column to a table which defaults to False, but I wanted all existing records to have the data set to "True". In django I would have done `migrations.RunPython()`. The piccolo docs state clearly not to direclty import tables into the migrations but it feels to me that there's a bit of gap in the docs regarding how to "massage data" during a migration given that limitation.

**Comment by dantownsend** [comment]
@trondhindenes You're right - the docs don't cover the grey areas around migrations very well.

It says never to import tables directly into migrations. It might be OK to do this in some situations - e.g. if you're pretty confident that table won't get deleted from your codebase in the future.

Alternatively, I tend to copy the relevant tables into the migration file.

```python
ID = 'abc123'

class MyTable(Table):
    name = Varchar()

async def update_rows():
    await MyTable.update({MyTable.name: 'some_name'})

async def forwards():
    manager = MigrationManager(migration_id=ID, app_name="my_app")
    manager.add_raw(update_rows)
    return manager
```

The docs should really show this too, as it is possible to run raw SQL in migrations:

```python
ID = 'abc123'

class RawTable(Table):
    pass

async def update_rows():
    await RawTable.raw('update my_table set name={}', 'some_name')

async def forwards():
    manager = MigrationManager(migration_id=ID, app_name="my_app")
    manager.add_raw(update_rows)
    return manager
```

**Comment by trondhindenes** [comment]
nice, yes those are exactly the tips and tricks I was looking for :-)

**Comment by dantownsend** [comment]
I've updated the docs now to have more examples:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/migrations/create.html
