### ISSUE TITLE
schema generate incorrectly generates an error when a column is not null and there is no default

### ISSUE THREAD

**Issue by gmos** [piccolo-orm/piccolo#446]
schema generate incorrectly generates an error when a column is not null and there is no default.

This check is wrong.  Though Postgres enforces this rule on ALTER TABLE to handle existing rows, it is perfectly legal to have not null without a default on existing columns.
Propose to remove the check.

**Comment by dantownsend** [comment]
Yeah, it's probably triggering this error:

https://github.com/piccolo-orm/piccolo/blob/5aea0fdc4f40a99615f534ec49a38b242a5f5cb0/piccolo/columns/base.py#L461

It could be removed, or turned into a warning. What do you think?

**Comment by gmos** [comment]
Yup, that is the one.

Problem is that no default is required when creating a new table and when adding a column to an empty table, whereas it’s required when adding a column to a non-empty table.

So you only know for sure when either a schema extraction or a migration is running.

With a schema extraction you do not know where the extraction is used for, most likely not to add a column that already exists in the DB.  Perhaps a warning form the extraction.

A warning in the class itself  would fire each and every instantiation.  Surely not good.

Remains a check before an alter table adding such column during migration.  But then, what would you do?  Abort?  That is just what the database will already do.

So, no error, no warning seems the best to me.

**Comment by dantownsend** [comment]
Cool, I agree that removing it in the best option.

I'm on the road currently, but will remove it ASAP in the next release.

**Comment by backwardspy** [comment]
would this also resolve #207? i just commented there and then noticed this issue. :)

**Comment by dantownsend** [comment]
@backwardspy You're right - the underlying cause seems to be the same 👍
