### ISSUE TITLE
When table contains ForeignKey(null=False) using ModelBuilder.build_sync(SomeTable) raises error

### ISSUE THREAD

**Issue by fiolet069** [piccolo-orm/piccolo#461]
Hi, maybe I've found bug. 

I have this scheme:

    class AppUser(Table):
        email = Varchar(unique=True)
        password = Varchar()

    class Book(Table):
        name = Varchar(length=50)
        app_user = ForeignKey(
            references='AppUser',
            null=False,
        )

When I use ModelBuilder to create book in DB I get error ValueError.
Code for creation record in db:

    user = ModelBuilder.build_sync(AppUser)
    book = ModelBuilder.build_sync(Book, defaults={Book.app_user: user})

Information of raised error:

    .venv/lib/python3.10/site-packages/piccolo/testing/model_builder.py:80: in build_sync
        return run_sync(
    .venv/lib/python3.10/site-packages/piccolo/utils/sync.py:25: in run_sync
        return loop.run_until_complete(coroutine)
    ../../.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py:641: in run_until_complete
        return future.result()
    .venv/lib/python3.10/site-packages/piccolo/testing/model_builder.py:50: in build
        return await cls._build(
    .venv/lib/python3.10/site-packages/piccolo/testing/model_builder.py:97: in _build
        model = table_class()
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    
    self = <Book: None>, ignore_missing = False, exists_in_db = False, kwargs = {}, column = Book.app_user - ForeignKey, value = None
    
        def __init__(
            self,
            ignore_missing: bool = False,
            exists_in_db: bool = False,
            **kwargs,
        ):
            """
            Assigns any default column values to the class.
        
            :param ignore_missing:
                If ``False`` a ``ValueError`` will be raised if any column values
                haven't been provided.
            :param exists_in_db:
                Used internally to track whether this row exists in the database.
        
            """
            self._exists_in_db = exists_in_db
        
            for column in self._meta.columns:
                value = kwargs.pop(column._meta.name, ...)
        
                if value is ...:
                    value = kwargs.pop(
                        t.cast(str, column._meta.db_column_name), ...
                    )
        
                if value is ...:
                    value = column.get_default_value()
        
                    if isinstance(value, Default):
                        value = value.python()
        
                    if (
                        (value is None)
                        and (not column._meta.null)
                        and not ignore_missing
                    ):
    >                   raise ValueError(f"{column._meta.name} wasn't provided")
    E                   ValueError: app_user wasn't provided
    
    .venv/lib/python3.10/site-packages/piccolo/table.py:306: ValueError

But if I config default=0 in ForeignKey field It works fine:

        app_user = ForeignKey(
            references='AppUser',
            null=False,
            default=0,
        )

May be reason of this error that default value of ForeignKey equels None. When ModelBuilder is trying init Table without value (use default values of piccolo built-in types) and this code
[go to code](https://github.com/piccolo-orm/piccolo/blob/master/piccolo/table.py#L301)

                    if (
                        (value is None)
                        and (not column._meta.null)
                        and not ignore_missing
                    ):
    >                   raise ValueError(f"{column._meta.name} wasn't provided")

see that app_user (ForeignKey) value is None and null param this column is False so raise error.

Please, check this case. May be is It normal behaviour? For me it's strange.

**Comment by dantownsend** [comment]
@fiolet069 Thanks for reporting this - you're right, it does seem to be a bug. Looking into it.

**Comment by dantownsend** [comment]
I found the issue - will push a fix asap.

**Comment by fiolet069** [comment]
@dantownsend Thank you for so great tool.

**Comment by dantownsend** [comment]
The fix is on PyPI now - version 0.71.1. Hopefully should fix the problem. Thanks again for reporting this 👍

**Comment by scott2b** [comment]
I am still seeing this in 0.73

**Comment by dantownsend** [comment]
@scott2b Interesting - I'll try and replicate the issue. Perhaps some more unit tests are required.
