### ISSUE TITLE
the 'package' argument is required to perform a relative import

### ISSUE THREAD

**Issue by smythp** [piccolo-orm/piccolo#465]
My apologies if this is a basic question, but I'm getting an error when attempting to perform an auto migration with postgres.

```
$ piccolo migrations new <package-name> --auto
Creating new migration ...
The command failed.
the 'package' argument is required to perform a relative import for '.#2022-03-19T19-57-34-799043'
```

The rest of the output suggests usage for the migrations command, but the command does not seem malformed, and I've checked the package name. What could be causing this?

**Comment by smythp** [comment]
I realized there were hidden files in my migrations folder that triggered the error. After clearing out those files, the migration worked. Closing, with thanks.

**Comment by dantownsend** [comment]
No problem - glad you got it sorted. 👍
