### ISSUE TITLE
[Questions] DB connection pool for long running process

### ISSUE THREAD

**Issue by dashsatish** [piccolo-orm/piccolo#478]
Hi @dantownsend 
Is there a way we can create a DB connection pool for a long running Python process.
For FastAPI server I can see the docs at https://piccolo-orm.readthedocs.io/en/latest/piccolo/engines/postgres_engine.html#connection-pool

Couldn't find a related doc for a long running python process, more importantly running it as a sync command.

Any help would be appreciated.

**Comment by dantownsend** [comment]
Hi @dashsatish.

You could try something like this:

```python
from piccolo.engine import engine_finder, PostgresEngine
from piccolo.utils.sync import run_sync

# This gets the DB from piccolo_conf.py
DB: PostgresEngine = engine_finder()

# We can start the connection pool synchronously:
run_sync(DB.start_connection_pool())

# This will now be using the connection pool:
MyTable.select().run_sync()
```

If you create lots of processes (perhaps using `ProcessPoolExecutor`) there's the possibility of having many connection pools. You can specify a smaller pool size - if it's sync anyway, you probably only need a pool size of 1.

```python
run_sync(DB.start_connection_pool(max_size=1))
```

Does that help?

**Comment by dashsatish** [comment]
Perfecto! Thanks a lot Daniel. Can we add in some docs under some section would be super useful (I believe teams spinning worker processes to consume events might need this)

**Comment by dantownsend** [comment]
You're right, it should be mentioned in the docs that a connection pool can be started synchronously.

You can configure the pool with certain parameters which controls how fresh it is:

https://github.com/MagicStack/asyncpg/blob/bd192623d05668b5919d55d3b9a62629594e2fb7/asyncpg/pool.py#L1016-L1026

For example, you can set `max_queries` and `max_inactive_connection_lifetime`. You can pass these values into Piccolo's `start_connection_pool` and they're passed to asyncpg.

**Comment by dashsatish** [comment]
Should I keep this open or close it?

**Comment by dashsatish** [comment]
Solution provided.
