### ISSUE TITLE
filter between datetime range

### ISSUE THREAD

**Issue by ideentwickler** [piccolo-orm/piccolo#48]
django orm
`startdate = datetime.now() - timedelta(days=7)`
`enddate = datetime.now()`
`Model.objects.filter(created_at__range=[startdate, enddate]`

is there already a possibility to run this with piccolo without a need for raw sql?

**Comment by sinisaos** [comment]
@ideentwickler I think you could do something like this
```
startdate = datetime.now() - timedelta(days=7)
enddate = datetime.now()
m = Model
m.select().where(
    (m.created_at >= startdate) & (m.created_at <= enddate)
)
```
[where()](https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_clauses/where.html) is really powerful in Piccolo
