### ISSUE TITLE
Transaction object has no method add

### ISSUE THREAD

**Issue by theelderbeever** [piccolo-orm/piccolo#482]
I am attempting to use a transaction in one of my migrations however, I am unable to add to the transaction due to the `add` method not existing.  I believe I am following the docs [here](https://piccolo-orm.readthedocs.io/en/0.7.7/piccolo/query_types/transactions.html) correctly.

The error
>🚀 Running 1 migration:
running 2022-04-08T10:51:00:796722
The command failed.
'Transaction' object has no attribute 'add'

This is part of my migration
```python
async def forwards():
    manager = MigrationManager(migration_id=ID, app_name="", description=DESCRIPTION)
    transaction = Table._meta.db.transaction()

    print(f"running {ID}")

    transaction.add(
        Table.raw(
            """ALTER TABLE task__logs DROP CONSTRAINT task__logs_pkey;"""
        )
    )
    transaction.add(Table.raw("""ALTER TABLE task__logs DROP COLUMN id;"""))
    transaction.add(
        Table.raw(
            """
        ALTER TABLE
            task__logs
        ADD CONSTRAINT task__logs_pkey
        PRIMARY KEY (task_name, started_at);
        """
        )
    )
```

**Comment by dantownsend** [comment]
Yeah, there's two approaches to transactions. One is using [atomic](https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_types/transactions.html#atomic).

To use this you just need to tweak your code:

```python
# Change from this:
transaction = Table._meta.db.transaction()

# To this:
transaction = Table._meta.db.atomic()

# Then use the add method:
transaction.add(Table.raw("a query"))
transaction.add(Table.raw("another query"))

# And finally run it:
await transaction.run()
# Or
transaction.run_sync()
```

There's another approach which uses a [context manager](https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_types/transactions.html#transaction):

```python
async with Table._meta.db.transaction():
    await Table.raw('a query')
    await Table.raw('another query')
```
It uses some Python black magic here, so you don't need to use the `add` method. It basically attaches a transaction to the current async task, and any queries done within the context manager run in the transaction.

**Comment by theelderbeever** [comment]
Okay awesome I will give that a go!
