### ISSUE TITLE
[Question] Get a cursor from Table instance

### ISSUE THREAD

**Issue by satishdash** [piccolo-orm/piccolo#490]
Hi,
Needing a couple of clarifications:
1) When I do a select query, it returns a list of rows. Instead can it return an iterator or is there a way to fetch rows using a cursor without using asyncpg driver natively.?

2) Can I convert a Table instance or a query result to a pandas dataframe directly, like sqlalchemy. I saw a few examples using asyncpg but if there's something more advanced yet internal to piccolo we'd like to know it.
(Really appreciate the timely responses and involvement for our previous clarifications, thanks)

**Comment by dantownsend** [comment]
When doing a select, if there are loads of rows, you can use the batch feature:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_clauses/batch.html

That uses a cursor under the hood to iterate through the results.

Piccolo doesn't have builtin support for Pandas dataframes at the moment.

**Comment by sinisaos** [comment]
@satishdash Sorry if I didn't understand well, but you can easily use pandas dataframe because the query result is a list of dicts.
```python
import pandas as pd

@app.get("/tasks/")
async def tasks():
    data = await Task.select().order_by(Task.id)
    df = pd.DataFrame(d)
    print(df)
    return data
```

**Comment by dashsatish** [comment]
Thanks @dantownsend @sinisaos 

@sinisaos Sorry if I my question was not too clear. Daniel's answer is what would be a better solution as we do not all the rows at once in a data frame or at once to write to a csv. Additionally, I think it'll be an implementation in Pandas to support an `asyncpg` connection to fetch records from the data store.

**Comment by dantownsend** [comment]
Thanks both, I'll close this for now - feel free to reopen if needed.
