### ISSUE TITLE
`pip install piccolo[all]` fails on Windows due to `uvloop` dependency

### ISSUE THREAD

**Issue by jack1142** [piccolo-orm/piccolo#491]
`uvloop` does not support Windows so this dependency should only be installed if the OS is not Windows.
This can be achieved with the environment marker:
```
uvloop>=0.12.0; sys_platform != "win32"
```

**Comment by dantownsend** [comment]
@jack1142 Thanks a lot for reporting this - I've created a PR to fix it.

**Comment by dantownsend** [comment]
The fix is on PyPI - hopefully that fixes the issue.
