### ISSUE TITLE
[Question] about custom column implementation

### ISSUE THREAD

**Issue by WintonLi** [piccolo-orm/piccolo#496]
Hi,

I started to use Piccolo recently, and am very impressed by its functionalities. Thank you all for developing such an elegant async backend framework!

Now I am struggling in creating a custom column type. Perhaps I miss something, but there seems to be no documentation regarding how to do that.

My goal is simple: to create a column type which is fundamentally a Varchar type but has a property called 'choice_name'. What I have tried is to inherit the Varchar class like this:

```python
from piccolo.columns import Varchar

class ChoiceVarchar(Varchar):
    def __init__(self, *args, choice_name: str = '', **kwargs):
        self.choice_name = choice_name
        super().__init__(*args, **kwargs)
```
In my table:

```python
from piccolo.table import Table

class FundMeta(Table):
    code = ChoiceVarchar(64, choice_name='CODE')
```

When I tried to create migrations with the --auto option, I received the following attribute error:
```shell
  File "c:\works\codes\qa_backend\venv\lib\site-packages\piccolo\apps\migrations\auto\schema_differ.py", line 480, in new_table_columns
    expect_conflict_with_global_name=getattr(
AttributeError: type object 'UniqueGlobalNames' has no attribute 'COLUMN_CHOICEVARCHAR'

```

So does it mean I need to register the custom type to `UniqueGlobalNames` somewhere? If so how can I to that?

Thanks so much!

**Comment by dantownsend** [comment]
I've released the fix - 0.74.2 on PyPI. Hopefully it fixes the issue 👍

**Comment by WintonLi** [comment]
@dantownsend Thank you for getting back so quickly and explaining these to me. Very clear and helpful. 

Please let me know if you want to document how to customize column types. I am very happy to contribute.

**Comment by dantownsend** [comment]
@WintonLi Thanks, that would be great. Maybe a section on this page?

https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/advanced.html

**Comment by WintonLi** [comment]
> @WintonLi Thanks, that would be great. Maybe a section on this page?
> 
> https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/advanced.html

More than happy. I will do it on this Friday.

**Comment by dantownsend** [comment]
@WintonLi Awesome, thanks!

**Comment by WintonLi** [comment]
@dantownsend I added a new section to the schema/advanced doc and created a pull request. Please see if it's ok.

**Comment by dantownsend** [comment]
Going to close now, as the solution is now in the docs - thanks.
