### ISSUE TITLE
[Question] How to cast a column attribute for filter clauses

### ISSUE THREAD

**Issue by dashsatish** [piccolo-orm/piccolo#502]
Hi,
I want to compare a `Timestampz` column which after retrieval comes out as a `datetime.datetime` object. Is there a way to cast it as a `date` object in a where clause. I'm unable to do it.

E.g.
```
Employee.select().where(Employee.created_at.date() == datetime.datetime.today())
```
Postgres allows filter clauses after casting timestamptz cols (`::date`) with ISO-8601 strings.

Any help appreciated!

**Comment by dantownsend** [comment]
@dashsatish It's not something we currently support, but you can try using `WhereRaw`:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_clauses/where.html?highlight=whereraw#whereraw

So it will be something like:

```python
from piccolo.columns.combination import WhereRaw

await Employee.select().where(WhereRaw('created_at::date = {}', datetime.datetime.today())
```

**Comment by dashsatish** [comment]
Thanks @dantownsend . Can `WhereRaw` combined with other filter expressions in the `where` method?

**Comment by dantownsend** [comment]
@dashsatish Yeah, you should be able to combine it like usual:

```python
await Employee.select().where(
    WhereRaw('created_at::date = {}', datetime.datetime.today()),
    Employee.department == 'tech'
)
```
