### ISSUE TITLE
Get 'another operation is in progress' error when using run_sync() in FastAPI endpoint

### ISSUE THREAD

**Issue by WintonLi** [piccolo-orm/piccolo#505]
First there is a Piccolo table `ItemMeta`, and in an endpoint of my FastAPI app (scaffolded by Piccolo's app new cli):
```python
...
from .tables import ItemMeta
from pydantic import BaseModel

class ItemSimple(BaseModel)
    name: str
    code: str

@my_router.get("/list-items", response_model=List[ItemSimple])
def list_items():
    """return a list of simplified items"""
    return ItemMeta.select(ItemMeta.name, ItemMeta.code).run_sync()  # got 'another operation is in progress' error
```
 
A request to the endpoint produces the following error:
```
...
File "asyncpg\protocol\protocol.pyx", line 323, in query
  File "asyncpg\protocol\protocol.pyx", line 707, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress
```
There is no problem if the the endpoint is `async` e.g.:
```Python
...

# no problem for this endpoint
@my_router.get("/list-items", response_model=List[ItemSimple])
async def list_items():
    """return a list of simplified items"""
    return await ItemMeta.select(ItemMeta.name, ItemMeta.code)
```

I tested the run_sync() statement in Piccolo shell and it works as expected. However, it produces the same error in a `pdb` debug interactive shell.

(I use run_sync() beacause I want to cache some output, and the caching library seems to work on sync functions only)

**Comment by dantownsend** [comment]
@WintonLi The problem here is to do with the connection pool.

The solution for now is:

```python
return ItemMeta.select(ItemMeta.name, ItemMeta.code).run_sync(in_pool=False)
```

`run_sync` used to bypass the connection pool by default. It got changed fairly recently, so `run_sync` tries to use the connection pool if it's available, but it can cause issues when `run` and `run_sync` are used in the same app.

I think I'll change back so `run_sync` is `in_pool=False` by default.

**Comment by WintonLi** [comment]
Cool thanks for your help!

**Comment by dantownsend** [comment]
No worries

**Comment by WintonLi** [comment]
> I think I'll change it back so `run_sync` is `in_pool=False` by default.

I am curious why its default value is `True` now. Is it for a better performance? Just my personaly usage experience, most of the time I need `in_pool=True`.

**Comment by dantownsend** [comment]
It was changed to `True` because reusing connection is slightly faster. When an app is purely using `run_sync` it's beneficial. But honestly, it's rare for Piccolo to be used that way, and given that it sometimes causes these asyncpg errors, isn't really worth it.

**Comment by WintonLi** [comment]
Understood. Thanks again for the explanation.
