### ISSUE TITLE
async ward tests fail with piccolo 0.75.0, pass with piccolo 0.74.4

### ISSUE THREAD

**Issue by backwardspy** [piccolo-orm/piccolo#536]
i've put together a small project here to help replicate the issue: https://github.com/backwardspy/piccolo-ward-async-repro

i have a project with around 100 [ward](https://github.com/darrenburns/ward/blob/master/README.md) tests. most of those tests fail on piccolo 0.75.0 with the following error:

```
FixtureError: Unable to resolve fixture '[redacted]'
    ↓ caused by ↓
RuntimeError: There is no current event loop in thread 'MainThread'.
```

running the tests on piccolo 0.74.4 works fine.

i believe this is (at least indirectly) caused by the changes to the async event loop handling in piccolo. that said, i'm not sure if this is actually an issue with piccolo, or just an issue with ward that has now been illuminated due to the aforementioned piccolo changes.

i appreciate any thoughts/suggestions. great work on piccolo!

**Comment by dantownsend** [comment]
In the last version of Piccolo we slightly changed how `run_sync` works, because it was using a function in asyncio which was marked as deprecated in Python 3.10. 

It sounds like there are some edge cases where the new one is failing.

Stay on Piccolo 0.74.4 for now (there aren't any other major changes in 0.75.0) until we can figure out a fix.

We're catching the `RuntimeError` in `run_sync`, so I wonder how that exception is escaping ... it's a strange one.

<img width="582" alt="Screenshot 2022-06-08 at 17 12 37" src="https://user-images.githubusercontent.com/350976/172665991-ad83c4e1-5de4-4e52-bd0d-998b2ef4c1f6.png">

**Comment by backwardspy** [comment]
i'm not actually using `run_sync` anywhere in my code, and in my case this exception is originating in ward, specifically from this line:
```python
fixture.resolved_val = asyncio.get_event_loop().run_until_complete(arg(**args_to_inject))
```
i must admit i'm don't fully understand how the various asyncio event loop functions fit together, but my guess is previously piccolo was setting up the event loop in a certain way and ward was able to piggyback off of that for its own purposes.

**Comment by backwardspy** [comment]
yeah i am using 3.10.5. i can try the latest 3.11 version to see if it helps at all

**Comment by dantownsend** [comment]
I've dug into it a bit more.

I came across a suggestion in this thread: https://github.com/python/cpython/issues/93453

If I use `asyncio.get_event_loop_policy().get_event_loop()` in `run_sync` then it works:

```python
from __future__ import annotations

import asyncio
import typing as t
from concurrent.futures import ThreadPoolExecutor


def run_sync(coroutine: t.Coroutine):
    """
    Run the coroutine synchronously - trying to accommodate as many edge cases
    as possible.
     1. When called within a coroutine.
     2. When called from ``python -m asyncio``, or iPython with %autoawait
        enabled, which means an event loop may already be running in the
        current thread.
    """
    try:
        # This bit is new:
        loop = asyncio.get_event_loop_policy().get_event_loop()
    except RuntimeError:
        # No current event loop, so it's safe to use:
        return asyncio.run(coroutine)
    else:
        if not loop.is_running():
            return loop.run_until_complete(coroutine)

        # We're already inside a running event loop, so run the coroutine in a
        # new thread:
        new_loop = asyncio.new_event_loop()

        with ThreadPoolExecutor(max_workers=1) as executor:
            future = executor.submit(new_loop.run_until_complete, coroutine)
            return future.result()
```

I need to still wrap my head around it a bit more before pushing a fix.

**Comment by dantownsend** [comment]
I had to take a different approach in the end.

Basically, the core problem is Piccolo's `create_tables` function is sync only, and wasn't working inside `ward`. I had a deep dive into the `ward` and `asyncio` codebases, and the best solution was just to make an async version of `create_tables`.

So in the next release, you'll be able to do this instead:

```python
from piccolo.table import create_db_tables, drop_db_tables

@fixture
async def tables():
    table_classes = Finder().get_table_classes()
    await create_db_tables(*table_classes)
    yield
    await drop_db_tables(*table_classes)
```
