### ISSUE TITLE
OneToOne filed and sorted columns in admin view

### ISSUE THREAD

**Issue by tigerline86** [piccolo-orm/piccolo#538]
Hello!
first of all, it's awesome framework and ecosystem! Great Work!

can't find, is it supported OneToOne field like in Django?

**Comment by dantownsend** [comment]
Hi @tigerline86 Thanks for the kind words.

Piccolo doesn't really have anything directly equivalent to `OneToOneField` in Django at the moment.

You can set foreign keys as unique:

```python
class Manager(Table):
    name = Varchar()

class Band(Table):
    name = Varchar()
    manager = ForeignKey(Manager, unique=True)
```

But there's no fast way of looking up the `band` for a `manager` in the example above.

You would have to do:

```python
manager = await Band.objects().get(Band.name == 'Guido')

# To get the reverse side of the relationship
band = await Band.objects().get(Band.manager == manager)
```

We will probably add support for it at some point - we just need to decide on an API for it.
