### ISSUE TITLE
Complex UniqueConstraint for tables

### ISSUE THREAD

**Issue by northpowered** [piccolo-orm/piccolo#572]
Are there any variants to create complex **UniqueConstraint** (ex. with 2 fields), like in SQLAlchemy?

SQLAlchemy example:
``` python
__table_args__ = (
        UniqueConstraint('foo_id', 'bar_id',
                         name='_foobar_constraint'),
    )
foo_id = Column(ForeignKey('foos.id'), nullable=False)
bar_id = Column(ForeignKey('bars.id'), nullable=False)
```

Or maybe it can be an enhancement?

**Comment by dantownsend** [comment]
It isn't available at the moment unfortunately, but is high on our priority list, as it is often requested.

If you're using Piccolo migrations, you can create a manual one which creates the unique constraint directly, using SQL:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/migrations/create.html#running-raw-sql
