### ISSUE TITLE
[Bug] Non unique PK with default UUID4()

### ISSUE THREAD

**Issue by northpowered** [piccolo-orm/piccolo#573]
### Context:
We want to use **UUID4** as a PK for a table

### Model example
```python
class Foo(Table, tablename="foo"):

    id = Text(primary_key=True, index=True, default=str(uuid4()))
    name = Text(unique=True, index=True, null=False)
    active = Boolean(nullable=False, default=True)
```

If we are working with piccolo-api (ex. piccolo-admin  GUI), default value for a column generating at once.
So it`s unable to add rows with piccolo-admin one by one, without application restarting.
All tries after the first one, raises
```
asyncpg.exceptions.UniqueViolationError: duplicate key value violates unique constraint "foo_pkey"
```

If we are working directly from the code, we are able to do smth like this:
```python
new_id = str(uuid4())
foo: T_F = cls(
    id = new_id,
    name = name,
    active = active
)
try:
    resp = await cls.insert(foo)
#......
```
and everything is fine.

Maybe  I`m doing smth wrong, but how I can manage tables from piccolo-admin with "single" PK?

Official doc says about UUID column type, but it there is no difference.

ADDITION:
Using **UUID** column is incompatible with ForeignKeys
```
foreign key constraint "m2_m_foo_bar_foo_fkey" cannot be implemented
DETAIL:  Key columns "foo" and "id" are of incompatible types: text and uuid.
```

**Comment by sinisaos** [comment]
@northpowered I can reproduce the problem only if I use a `Text` column as in your example. If I use the `UUID` ([docs](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/defining.html#primary-key)) column like this
```python
class Foo(Table, tablename="foo"):
    id = UUID(primary_key=True, index=True) 
    name = Text(unique=True, index=True, null=False)
    active = Boolean(nullable=False, default=True)

class Bar(Table, tablename="bar"):
    name = Text(unique=True, index=True, null=False)
    foo_items = ForeignKey(references=Foo)
```
everything is fine in both cases (`PK` and `FK`). I think the main problem is that you are not using the Piccolo ORM `UUID` column, but the `Text` column and that is causing the incompatibility. Hope that helps.

**Comment by dantownsend** [comment]
With the default, if you provide a function instead, then it should work properly:

```python
def generate_uuid():
    return str(uuid4())

class Foo(Table, tablename="foo"):
    id = Text(primary_key=True, index=True, default=generate_uuid)
```

**Comment by northpowered** [comment]
> @northpowered I can reproduce the problem only if I use a `Text` column as in your example. If I use the `UUID` ([docs](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/defining.html#primary-key)) column like this
> 
> ```python
> class Foo(Table, tablename="foo"):
>     id = UUID(primary_key=True, index=True) 
>     name = Text(unique=True, index=True, null=False)
>     active = Boolean(nullable=False, default=True)
> 
> class Bar(Table, tablename="bar"):
>     name = Text(unique=True, index=True, null=False)
>     foo_items = ForeignKey(references=Foo)
> ```
> 
> everything is fine in both cases (`PK` and `FK`). I think the main problem is that you are not using the Piccolo ORM `UUID` column, but the `Text` column and that is causing the incompatibility. Hope that helps.

I know, but UUID is incompatible with ForeignKeys

**Comment by northpowered** [comment]
> With the default, if you provide a function instead, then it should work properly:
> 
> ```python
> def generate_uuid():
>     return str(uuid4())
> 
> class Foo(Table, tablename="foo"):
>     id = Text(primary_key=True, index=True, default=generate_uuid)
> ```

Yes, that works fine!
My mistake was trying to use generator instead of usual method
