### ISSUE TITLE
Can a db extra node be passed to batch query executions?

### ISSUE THREAD

**Issue by guruvignesh01** [piccolo-orm/piccolo#578]
While checking the batch documentation https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_clauses/batch.html#batch, I couldn't find any configuration for passing read replica db connection as an extra node.

**Comment by sinisaos** [comment]
@guruvignesh01 Not sure but I think this should work ([docs](https://piccolo-orm.readthedocs.io/en/latest/piccolo/engines/postgres_engine.html#source)) because you can pass `node` argument to [run() method](https://github.com/piccolo-orm/piccolo/blob/master/piccolo/query/base.py#L167).
```python
async with await YourTable.select().batch(batch_size=100).run(node="your_read_replica") as batch:
    async for _batch in batch:
        print(_batch)
```

**Comment by dantownsend** [comment]
Yeah, it doesn't work at the moment unfortunately.

It's not a huge change to Piccolo to make it work, so hopefully we can add it soon.

**Comment by dantownsend** [comment]
We just need to change this:

https://github.com/piccolo-orm/piccolo/blob/0c44bb22be451e27318ddc2594e7e5a775494f80/piccolo/engine/postgres.py#L393-L397

So instead it's something like:

```python
    async def batch(self, query: Query, batch_size: int = 100, node: t.Optional[str] = None) -> AsyncBatch:
        engine = self.extra_nodes.get(node) if node else self 
        connection = await engine.get_new_connection()
        return AsyncBatch(
            connection=connection, query=query, batch_size=batch_size
        )
```

**Comment by sinisaos** [comment]
@guruvignesh01 @dantownsend Sorry for the wrong answer. I didn't know that.

**Comment by dantownsend** [comment]
@sinisaos No worries - what you suggested made sense.

**Comment by dantownsend** [comment]
@sinisaos Do you want to have a go at a PR for this? No pressure - I might be able to do it later today.

**Comment by sinisaos** [comment]
@dantownsend No problem, I can try.

**Comment by guruvignesh01** [comment]
Thanks @sinisaos @dantownsend

**Comment by dantownsend** [comment]
Fixed by https://github.com/piccolo-orm/piccolo/pull/579
