### ISSUE TITLE
Renaming column name does not reflect change in the database

### ISSUE THREAD

**Issue by sumitsharansatsangi** [piccolo-orm/piccolo#585]
I had a column with the name `customerAddress`, changed it to `customer_address`, but the change does not reflect it in the database after applying migration.

**Comment by dantownsend** [comment]
When you created the migration, did it ask you something like `Did you rename customerAddress to customer_address?`

Can you double check if the migration file has something like this in it:

```python
async def forwards():
    manager = MigrationManager(
        migration_id=ID, app_name="my_app"
    )

    manager.rename_column(
        table_class_name="MyTable",
        tablename="my_table",
        old_column_name="customerAddress",
        new_column_name="customer_address",
        ...
    )
```

**Comment by sumitsharansatsangi** [comment]
Sorry, Haven't added, `--auto`, with the command while doing migration.
