### ISSUE TITLE
[Bug] Strange behavor of default values for a Timestamp column

### ISSUE THREAD

**Issue by northpowered** [piccolo-orm/piccolo#588]
Model example:
```python
class Foo(Table, tablename="foos"):
# OTHER FIELDS
    created_at = Timestamp(nullable=True)
    updated_at = Timestamp(nullable=True)
    last_login = Timestamp(nullable=True)
    birthdate = Timestamp(nullable=True)
```
When I trying to create an object through a piccolo-admin, I`m catching an exception like this:

**(<class 'asyncpg.exceptions.NotNullViolationError'>, NotNullViolationError('null value in column "created_at" of relation "foos" violates not-null constraint'), <traceback object at 0x7fb6b03e0600>)**

I tried:

- Dropping and creating columns with migrations
- Dropping and creating columns with migrations one by one
- Setting DEFAULT value myself

The most interesting is when I dropped and created them one by one, previous fields passed right, but when I recreated the last column (**birthdate**) I saw an exception for a **created_at**

I`m interesting in **created_at = Timestamp()** column, for an auto filling the field with now()

When I`m working through an API (queries) all is fine, so IDK where I should create an issue 

--- UPD
The most strange thing for me is an exception from **asyncpg**, but as I already said, queries are working fine

**Comment by dantownsend** [comment]
Try using ``null`` instead of ``nullable``:

```python
class Foo(Table, tablename="foos"):
    created_at = Timestamp(null=True)
```

``Column`` accepts ``kwargs``, so Piccolo is allowing ``nullable`` without raising an error.
