### ISSUE TITLE
Filter not null values in where clause

### ISSUE THREAD

**Issue by rathourarv** [piccolo-orm/piccolo#59]
how can we filter not null values using piccolo?

example-:

Table Person :
                Name  |  Country
               Arvind  |  India
               Alien    |  NULL

I want to filter null values from the country column

    people = (
        Person.objects()
        .where(Person.country != None)
        .run_sync()
    )

expected: Arvind  |  India
actual:     empty list

**Comment by dantownsend** [comment]
@rathourarv This is a bug - I have a fix and will release it shortly. The syntax you are using should work.

Thanks for reporting it.

**Comment by rathourarv** [comment]
I guess this syntax should also work

people = (
    Person.objects()
    .where(Person.country is not None)
    .run_sync()
)

Correct me if I am wrong 🙂

**Comment by dantownsend** [comment]
@rathourarv It's very tricky to make `is` and `is not` work, because there's no magic method for this operator, which can easily be overriden.

https://stackoverflow.com/questions/15399024/does-the-is-operator-use-a-magic-method-in-python

It might be possible, but I haven't figured out how yet.

**Comment by dantownsend** [comment]
@rathourarv It's on PyPI now - give it a go, and let me know if you have any issues. Thanks!

https://pypi.org/project/piccolo/0.16.4

**Comment by rathourarv** [comment]
Thanks @dantownsend It's working...🙂
