### ISSUE TITLE
get_or_create prefetching only works on get, not create

### ISSUE THREAD

**Issue by backwardspy** [piccolo-orm/piccolo#597]
here is a reconstruction of the code with which i ran into this issue (table names anonymised.) in this example, `LinkTable` is an M2M table linking `Left` and `Right` together.

```python
In [40]: vars(
    ...:     await LinkTable.objects(
    ...:         LinkTable.left
    ...:     ).get_or_create(
    ...:         (LinkTable.left == left) & (LinkTable.right == right)
    ...:     )
    ...: )
Out[40]:
{'_exists_in_db': True,
 'pk': UUID('75093c27-59a6-4564-aab0-017f94dc1b39'),
 'left': UUID('6e13e214-54e4-4e61-97f7-dc25e8d9c7e4'),
 'right': UUID('5a164ce8-1a5f-4065-a5bc-6626e7509868'),
 '_was_created': True}

In [41]: vars(
    ...:     await LinkTable.objects(
    ...:         LinkTable.left
    ...:     ).get_or_create(
    ...:         (LinkTable.left == left) & (LinkTable.right == right)
    ...:     )
    ...: )
Out[41]:
{'_exists_in_db': True,
 'pk': UUID('75093c27-59a6-4564-aab0-017f94dc1b39'),
 'left': <Left: 6e13e214-54e4-4e61-97f7-dc25e8d9c7e4>,
 'right': UUID('5a164ce8-1a5f-4065-a5bc-6626e7509868'),
 '_was_created': False
```

as you can see, asking `get_or_create` to prefetch its results works when the record already exists, but not when a new one is created. would it be possible to make it work in both cases?

**Comment by dantownsend** [comment]
Yeah, it's a good point. I can see how the inconsistency is problematic.

At the moment we just save a new instance if it doesn't already exist, and then return it:

https://github.com/piccolo-orm/piccolo/blob/2c1a172b8bc4a1b0cb73a342581ab340145c9a3e/piccolo/query/methods/objects.py#L66-L70

There might be a better way of doing it. Some ideas:

 * If `prefetch` has been specified i.e. `LinkTable.objects(LinkTable.left)`, we do another query to get the associated objects.
 * I thought maybe we could do an `INSERT` with the `RETURNING` clause, but it doesn't seem like we can get data from joined tables.
 * Something else? 🤔

**Comment by dantownsend** [comment]
I've pushed a fix for now. We might be able to figure out something more efficient in the future.

**Comment by backwardspy** [comment]
that is perfect for my use case, thank you :)

**Comment by dantownsend** [comment]
No problem
