### ISSUE TITLE
Types for objects instances seem incorrect

### ISSUE THREAD

**Issue by dbanty** [piccolo-orm/piccolo#62]
If I run `mypy` on a file like this, it complains that I can't use a Varchar like a `str`. 

```python
from piccolo.table import Table
from piccolo.columns import Varchar

class Something(Table):
    a_string = Varchar(100)

def get_the_thing():
    Something.objects().first().run_sync().a_string.split(",")

```

Similar issue if, say, trying to `json.dumps` a column of type `JSONB`. Leads to `# type: ignore` and `cast` all over the place.

I don't know how possible if at all it would be to properly annotate the columns in a way that type checkers will know what the proper type is for instances. But hopefully it is!

**Comment by dantownsend** [comment]
@dbanty Yeah, this is something I want to get sorted.

I want Piccolo to work really well with MyPy, and this is the main pain point at the moment.

I'll try using `typing.cast` in `Table.__init__` to see if that helps.

**Comment by dbanty** [comment]
I assume it'll be difficult because you'll either lose type annotations with the query syntax (I assume that Column == value in a `.where` returns something that the `.where` expects and not a bunch of bools) or end up with `Union`s at run time. This is a larger issue in general with ORMs I think since the Table definition is the same class as the Result but the types of the attributes are, by definition, different.

I'm pretty sure that the way [sqlalchemy-stubs](https://github.com/dropbox/sqlalchemy-stubs/blob/master/sqlmypy.py) deals with this is with their mypy plugin so you might end up having to go down this route as well.

You could maybe make each `Column` type subclass their runtime counterpart? A bit hacky since it won't necessarily be true.

Another possible option would be to design database schemas more like how Pydantic defines theirs? Where the type annotation is used for each field and you can set it to a `Field` which I believe just returns `Any` so mypy ignores it? That might take some rework though in the API and therefore potentially breaking changes.

Lots to think about.  I'm always happy to discuss and bounce ideas around, especially if it helps lead to a better ORM for the Python ecosystem 😁
