### ISSUE TITLE
Feature: Custom SQL Functions

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo#620]
For example, postgres has the RANDOM() function. In order to replicate these sort of functions, it would be nice to have a Function type to allow custom queries and functions to be used in a order_by()

**Comment by cheesycod** [comment]
Right now, you have to use raw sql for these operations

**Comment by dantownsend** [comment]
You're right, this needs adding.

We have something similar called `WhereRaw`:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_clauses/where.html#whereraw

We need to add `SelectRaw`.

**Comment by dantownsend** [comment]
I just re-read this issue, and realised that you want to have custom SQL in the `order by` clause.

**Comment by cheesycod** [comment]
Yea

**Comment by cheesycod** [comment]
SelectRaw too would be nice

**Comment by cheesycod** [comment]
But really it would be nice to have a Function type

**Comment by cheesycod** [comment]
any updates?

**Comment by dantownsend** [comment]
I just need to refactor my PR, so we also have RawOrder.

**Comment by cheesycod** [comment]
Ah ok thanks

**Comment by dantownsend** [comment]
Fixed in [0.97.0](https://github.com/piccolo-orm/piccolo/releases/tag/0.97.0)
