### ISSUE TITLE
Confusion on primary key behavior

### ISSUE THREAD

**Issue by dbanty** [piccolo-orm/piccolo#63]
It seems like even though `primary` is an available argument to a `Column`, using it messes with migrations, preventing auto from working properly. Through some trial and error, I seem to have found that an `id` column is automatically added as the primary key to models. This wasn't at all clear to me in reading through the documentation.

I would like the ability to declare my own primary key column called `pk`, as `id` is a builtin function in Python and shadowing it (e.g. in a param to a function) can cause accidental mistakes. At the very least, it would be good to make this default behavior more obvious in the documentation.

**Comment by dashsatish** [comment]
@dbanty Please do have a look at https://github.com/piccolo-orm/piccolo/issues/32. I tripped on the same kinda issue.

**Comment by dantownsend** [comment]
You're both right - I didn't realise this functionality was completely undocumented.

I've added docs for now, but hope to make it more configurable at some point.

**Comment by aminalaee** [comment]
@dantownsend Can this be closed?

**Comment by dantownsend** [comment]
@aminalaee Yes, in v0.29.0 a custom primary key column can now be specified.
