### ISSUE TITLE
Add a `drop_table` method to the `Table` class

### ISSUE THREAD

**Issue by MiguelGuthridge** [piccolo-orm/piccolo#635]
Although (as per #283), it is possible to drop tables using the `drop_db_tables`, it can often be more clear to modify the table using a method attached directly to that table. This makes sense given that the `Table` class already has a `create_table` method.

**Comment by dantownsend** [comment]
There's a `drop_table`, but it's not at the top level. For example:

```python
await Band.alter().drop_table()
```

The reason it's like this was to make it less likely to be accidentally triggered. But the downside is it's less obvious that it exists!
