### ISSUE TITLE
Document JSONB Runtime Type

### ISSUE THREAD

**Issue by dbanty** [piccolo-orm/piccolo#64]
In converting from SQLAlchemy, I was expecting that declaring a column as `JSONB` would make it auto-serialize to/from JSON for me (particularly with orjson since I included that optional dependency). It would be a good idea to indicate that this column expects and returns a `str` to prevent confusion, and potentially include an option to auto ser/de.

**Comment by heliumbrain** [comment]
Related to [#49](https://github.com/piccolo-orm/piccolo_api/pull/49)? 

This should work now, if flagging it correctly as mentioned in the PR

@dantownsend this can be closed I guess?

**Comment by dantownsend** [comment]
Yes, I think it can be closed now. The JSON behaviour has been improved quite a bit in the latest release.

Copying the CHANGELOG here for reference. Thanks both.

-----------

With this schema:
```python
class RecordingStudio(Table):
    name = Varchar()
    facilities = JSON()
```

We can now do the following:

```python
RecordingStudio(
    name="Abbey Road",
    facilities={'mixing_desk': True}  # Will automatically be converted to a JSON string
).save().run_sync()
```

Similarly, when fetching data from a JSON column, Piccolo can now automatically deserialise it.

```python
>>> RecordingStudio.select().output(load_json=True).run_sync()
[{'id': 1, 'name': 'Abbey Road', 'facilities': {'mixing_desk': True}]

>>> studio = RecordingStudio.objects().first().output(load_json=True).run_sync()
>>> studio.facilities
{'mixing_desk': True}
```

**Comment by dantownsend** [comment]
Closing for now
