### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo#643]
Just a few nitpicks

1. Is ``run()`` needed for a transaction? (AKA is ``await Band.insert()`` and ``await Band.insert().run()`` different in a transaction
2. Why do we have to access a private attribute (``_meta``) to do a transaction?

**Comment by dantownsend** [comment]
> Is run() needed for a transaction? (AKA is await Band.insert() and await Band.insert().run() different in a transaction

`await Band.insert()` and `await Band.insert().run()` both work the same - so either is OK.

> Why do we have to access a private attribute (_meta) to do a transaction?

It's usually the most convenient way to access the engine instance. However, there are alternatives. For example:

```python
from piccolo.engine.finder import engine_finder

engine = engine_finder()

with engine.transaction():
    await Band.insert(...)
```

You're right, that both are these aren't clear from the [docs](https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_types/transactions.html?highlight=transaction#transaction).

Things we need to change:

[ ] Remove `run` from the example [here](https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_types/transactions.html?highlight=transaction#transaction).
[ ] Explain that `_meta.db` is used to access the engine.

**Comment by dantownsend** [comment]
The reason we put a lot of stuff in `_meta` is so it doesn't clash with column names. If we stored it `MyTable.db` instead of `MyTable._meta.db` it would break if someone had a column called `db`.
