### ISSUE TITLE
Add Postgres 15 and Python 3.11 to CI; remove Postgres 9.6

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#647]
Postgres 15 has now been released.

https://www.postgresql.org/support/versioning/

Postgres 9.6 isn't receiving updates any more. We need to keep our CI reasonably fast, so will have to drop it (Piccolo will still work with Postgres 9.6 though, so no immediate action required from users).

Python 3.11 will soon be released. For now, we can run tests against it using `3.11-dev`.

**Comment by virajkanwade** [comment]
@dantownsend PY 3.11 is out (24 Oct 2022). Maybe update from `3.11-dev` to `3.11`

**Comment by dantownsend** [comment]
@virajkanwade Good shout - I'll update it now.
