### ISSUE TITLE
Update `logging.getLogger()` to use` __name__` instead of `__file__`

### ISSUE THREAD

**Issue by Drapersniper** [piccolo-orm/piccolo#653]
`__name__` is recommended by the python docs - https://docs.python.org/3/library/logging.html#logger-objects

and using` __file__` can cause the following:
![image](https://user-images.githubusercontent.com/27962761/197415280-4d164aba-0514-4f44-bf9e-006e653d8662.png)

**Comment by dantownsend** [comment]
You're right! Good catch. We need to change this.
