### ISSUE TITLE
UUID field does not seem to allow passing in a UUID

### ISSUE THREAD

**Issue by scott2b** [piccolo-orm/piccolo#658]
I am not sure if this is by design? I have UUID fields that I don't want to be generated. I am getting the UUID from an external system. I have set the default on the field to None in order to prevent accidentally generating a UUID that is invalid for my scheme.

When I pass the known UUID into a create call, I get a Value error: the field was not provided.

I have tried passing in both strings and UUID objects (the python uuid.UUID class). Am I doing it wrong, or are UUID fields auto-generate-only?

**Comment by scott2b** [comment]
This appears to be something that may have been fixed. I just realized I was still on 0.73.0. I upgraded to 0.95.0 and I am now able to pass in my own value to the UUID field. This appears to work for passing either a string or a UUID object.

Thanks!

**Comment by dantownsend** [comment]
Yeah, you should be able to pass UUIDs in. I think this was a bug to do with `create` and nullable fields, that we fixed in a recent release. Glad your problem is sorted.
