### ISSUE TITLE
order_by appears not to be implemented for objects() with sqlite

### ISSUE THREAD

**Issue by scott2b** [piccolo-orm/piccolo#663]
This appears be sqlite specific. I am filing this issue as something to point to in my code comments to watch for resolution. @dantownsend, please let me know if you prefer a different approach to filing not-implemented issues. I realize that sqlite is not the top priority here.

I am seeing that when trying to use an `order_by` clause on an `objects()` query, I get a NotImplemented Error raised from `piccolo.query.base` line 262 (piccolo v. 0.95.0)

**workaround**

For now, I am using a select query instead.

**Comment by scott2b** [comment]
I have a Trend object:

```
class Trend(Table, tablename="trends"):

    timestamp: datetime.datetime = Timestamptz()
    ... (other fields)
```

migration:

```
async def forwards():
    manager = MigrationManager(
        migration_id=ID,
        app_name="myapp-trends",
        description=DESCRIPTION,
    )

    manager.add_table("Trend", tablename="trends")

    manager.add_column(
        table_class_name="Trend",
        tablename="trends",
        column_name="timestamp",
        db_column_name="timestamp",
        column_class_name="Timestamptz",
        column_class=Timestamptz,
        params={
            "default": TimestamptzNow(),
            "null": False,
            "primary_key": False,
            "unique": False,
            "index": True,
            "index_method": IndexMethod.btree,
            "choices": None,
            "db_column_name": None,
            "secret": False,
        },
    )

...
```

The query is:

```
trends = Trend.objects().order_by("timestamp").run_sync()
```

**Comment by scott2b** [comment]
ohhhh .... wait. My bad. I tried to use a string for the order by field.

**Comment by dantownsend** [comment]
Some of the methods accept strings, so it's fair to expect it to work with `order_by`.

I might change `order_by` at some point to accept strings (as well as columns).
