### ISSUE TITLE
add_m2m in transaction

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#674]
Hey,

Using `add_m2m` inside an transaction seems to be unsupported currently. Is this intentional (if so why) or something fixable?

I get this error:
```
piccolo.engine.exceptions.TransactionError: A transaction is already active - nested transactions aren't currently supported.
```

**Comment by dantownsend** [comment]
@powellnorma You're right. We use a transaction in the M2M code:

https://github.com/piccolo-orm/piccolo/blob/248c209cb3de26181aac907a68552f525dc182f2/piccolo/columns/m2m.py#L261

Which means if you wrap it in your own transaction you'll get an error, as nested transactions aren't currently supported.

I need to modify the code so it checks whether an transaction is currently active.

**Comment by dantownsend** [comment]
This will be fixed in the latest Piccolo version.
