### ISSUE TITLE
Foreign keys typing support

### ISSUE THREAD

**Issue by laggron42** [piccolo-orm/piccolo#680]
When using foreign keys and trying to access its attributes, type checkers will fail as it doesn't know what type the FK is pointing to.

```py
class ObjectA(Table):
  foo = Text()

class ObjectB(Table):
  a = ForeignKey(references=ObjectA)

# let object_b be an instance of ObjectB
object_b.a.foo # fails
```

This could be fixed using [TypeVar](https://docs.python.org/3/library/typing.html#typing.TypeVar)s and [Generic](https://docs.python.org/3/library/typing.html#typing.Generic). I already tried some edits and got it working pretty fast, I can help with a pull request (but I'm not very familiar with the library yet).

The new [TypeGuard](https://docs.python.org/3/library/typing.html#typing.TypeGuard) could also be used for ensuring the foreign instance was fetched (but it's only available in Python 3.10 and later, so probably not doable for now).

**Comment by dantownsend** [comment]
You're right - we can take the type inference to another level using `Generic` and `TypeVar`. I made an experimental branch a few months ago, and it seems hopeful.

I haven't used `TypeGuard` much yet. I'm hoping there's backwards support via `typing_extensions` so we can use it in older Python versions too.

If you want to have a go at a PR, that would be great.

**Comment by kantandane** [comment]
Is there any update about this ? I'm interested too. I'm discovering your awesome ORM, and I was surprised that my Session.user type was ForeignKey instead of User.

**Comment by dantownsend** [comment]
I've merged in a fix for this - it requires slightly new syntax (see PR https://github.com/piccolo-orm/piccolo/pull/914), but seems to work well.
