### ISSUE TITLE
sqlite timeout handling

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#687]
Hi, I often get `sqlite3.OperationalError: database is locked`, what would be the best way to evade this?

I thought about increasing the lock timeout, but am not sure how to correctly do this when using this library.

Here https://stackoverflow.com/a/39265148 the pragma-statement `PRAGMA journal_mode=WAL` is recommended. How would I use this with piccolo? I know I can execute raw sql, but doesn't this need to be re-executed for each connection?

Thank you for your help!

**Comment by powellnorma** [comment]
> I thought about increasing the lock timeout, but am not sure how to correctly do this when using this library.

Ok, one option seems to be to pass `timeout` to `SQLiteEngine.__init__`, which is then passed to `sqlite3.connect`:
https://docs.python.org/3/library/sqlite3.html#sqlite3.connect

> I know I can execute raw sql, but doesn't this need to be re-executed for each connection?

Perhaps in a similar fashion, by using the `factory` parameter? Will try

**Comment by dantownsend** [comment]
Passing in timeout seems like a good solution.

We could modify / subclass Piccolo's `SQLiteEngine` so it passed PRAGMAs automatically on each new connection.

**Comment by powellnorma** [comment]
Ok I have tried:
```
class SQLiteEngineMy(SQLiteEngine):
    async def get_connection(self):
        c = await super().get_connection()
        await c.execute("PRAGMA journal_mode=WAL")
        return c
```
But now I get `sqlite3.OperationalError: database is locked` every time on startup.

I also tried passing `timeout=30`, but got `sqlite3.OperationalError: database is locked` after ~6s

Anything else I can try?

**Comment by powellnorma** [comment]
> I also tried passing timeout=30, but got sqlite3.OperationalError: database is locked after ~6s

This was wrong, I get a timeout after 30s.. I guess I have a deadlock situation somehow..

**Comment by powellnorma** [comment]
Using `PRAGMA journal_mode=WAL` I can see that a `.db-wal` gets created, but even when combining it with `timeout=300` I still the the `database is locked` error frequently

**Comment by dantownsend** [comment]
Database locked errors are usually when multiple operations are being performed on the database at the same time which are incompatible.

Unfortunately, this is much easier to do with async code. Are you using anything like `asyncio.gather` to run multiple coroutines at the same time? Or using any transactions?

**Comment by powellnorma** [comment]
> Are you using anything like asyncio.gather to run multiple coroutines at the same time?

Not that I know of, however I run the app (in debug mode) with uvicorn + starlette + socketio, so I guess it is possible that the handling of requests overlap(?)

> Or using any transactions?

Yes I use transactions - One of the requests gives me a list, and I store every item of that list into the database. I use an transaction for the entire list (mostly just because this makes it faster)

> Database locked errors are usually when multiple operations are being performed on the database at the same time which are incompatible. Unfortunately, this is much easier to do with async code.

Yes, but isn't this the use case aiosqlite tries to cover? As I understand it, aiosqlite opens a new thread for each new sql connection. When does piccolo open such a new connection? Thank you for your help

**Comment by dantownsend** [comment]
> Yes, but isn't this the use case aiosqlite tries to cover? As I understand it, aiosqlite opens a new thread for each new sql connection. When does piccolo open such a new connection? Thank you for your help

With asyncio, each time you use `await` it switches to another coroutine, and each coroutine might have its own connection, so you can end up with a lot of connections.

Do you think you can post a very simple version of your app which re-creates the problem? I usually use Postgres for my apps, so there may be a bug somewhere with Piccolo and SQLite causing the problem.

**Comment by powellnorma** [comment]
> Do you think you can post a very simple version of your app which re-creates the problem?

Yes, please take a look here: https://github.com/powellnorma/piccolo-sqlite-problem

Note how I pass `timeout=300` to `SQLiteEngine`, but the `database is locked` error still seems to appear almost instantly

**Comment by sinisaos** [comment]
@powellnorma Sorry to jump into this discussion like this and sorry if I missed the point, but I tried two things with your repo. First I removed the db transaction from [here](https://github.com/powellnorma/piccolo-sqlite-problem/blob/65307c17a24b77598dc6e6f17a64f86829ec99e7/app.py#L14) and everything worked ok, but you probably don't want to do that. The second thing I tried was to leave the db transaction and add `await connection.execute("PRAGMA journal_mode = WAL")` [here](https://github.com/piccolo-orm/piccolo/blob/f3db5b3ac1dcb9bae22d7487ed92b3b7f693d74b/piccolo/engine/sqlite.py#L452) (not as a subclass of SqliteEngine as you did), but directly in the Piccolo ORM source code. I also had to set the timeout to at least 50 (`DB = SQLiteEngine("data.db", timeout=50)`) and everything was fine without the database is locked error. I haven't had time to test against Piccolo ORM and I don't know if it has any implications to library, but maybe it's a good starting point for solving your problem.

**Comment by powellnorma** [comment]
@sinisaos Thank you for investigating. I tried what you mentioned, but even adding the instruction directly into piccolo did not resolve the problem for me. Are you sure you enabled the transaction again? Otherwise, could you maybe publicize your code, so that I can reproduce this solution/workaround? Thank you

Also I think it is possible that `PRAGMA journal_mode = WAL` does help in reducing the occurrence of the problem, but not entirely stops it

**Comment by sinisaos** [comment]
@powellnorma I used your code without modification and you are right. If I start another transaction, the database gets locked again so adding `PRAGMA journal_mode = WAL` did not help. I've tried using `aiosqlite` directly like this
```python
import aiosqlite

async def add_list(prefix):
    async with aiosqlite.connect("data.db") as db:
        for i in range(100):
            name = f"{prefix}-{i}-{time():.9f}"
            command = f"INSERT INTO my_entity ('name') VALUES ('{name}');"
            await db.execute(command)
        await db.commit()
```
and everything is fine, so there must be a problem with the Piccolo Sqlite transaction code somewhere (Postgres works fine) but @dantownsend will probably know better.

**Comment by dantownsend** [comment]
@sinisaos thanks for taking a look.

I tweaked the code slightly, so it works completely standalone:

```python
# main.py
import asyncio
from time import time

from piccolo.columns.column_types import Varchar
from piccolo.engine.sqlite import SQLiteEngine
from piccolo.table import Table
from starlette.applications import Starlette
from starlette.responses import JSONResponse
import uvicorn


DB = SQLiteEngine()


class MyEntity(Table, db=DB):
    name = Varchar()


app = Starlette(debug=True)


async def add_list(prefix):
    async with MyEntity._meta.db.transaction():
        for i in range(100):
            name = f"{prefix}-{i}-{time():.9f}"
            await MyEntity.objects().get_or_create(MyEntity.name == name)
            await asyncio.sleep(0.05)


@app.route('/add-list/{prefix:str}')
async def r_add_list(request):
    prefix = request.path_params['prefix']
    try:
        await add_list(prefix)
        return JSONResponse(f"{prefix} -> done")
    except Exception as e:
        return JSONResponse(f"{prefix} -> {e}")


if __name__ == '__main__':
    MyEntity.create_table(if_not_exists=True).run_sync()
    uvicorn.run(app, host='127.0.0.1', port=64215, debug=True)

```

And then used this script to send a bunch of requests to the endpoint:

```python
# test_script.py
import asyncio
import random

import httpx


async def make_request(client: httpx.AsyncClient, index: int):
    number = random.randint(1, 100_000_000)
    url = f'http://127.0.0.1:64215/add-list/test-{number}'
    response = await client.get(url)
    assert response.status_code == 200
    print(f"Finished {index}")


async def main():
    async with httpx.AsyncClient(timeout=10) as client:
        await asyncio.gather(
            *[make_request(client, i) for i in range(100)]
        )
    print("Success")


if __name__ == '__main__':
    asyncio.run(main())
```

I couldn't get the database to lock. Does this code fail for you?

I'll try some more other tests.

**Comment by dantownsend** [comment]
Ah wait, I can see it now - my mistake. Will investigate.

**Comment by dantownsend** [comment]
I looked into it some more. Adding `timeout` definitely helped:

```python
DB = SQLiteEngine(timeout=100)
```

I changed one thing in Piccolo, which seemed to fix things. I changed this:

https://github.com/piccolo-orm/piccolo/blob/f3db5b3ac1dcb9bae22d7487ed92b3b7f693d74b/piccolo/engine/sqlite.py#L321

To:

```python
await self.connection.execute("BEGIN IMMEDIATE")
```

Here are the [docs](https://www.sqlite.org/lang_transaction.html#deferred_immediate_and_exclusive_transactions).

@powellnorma  Does that fix things for you?

**Comment by dantownsend** [comment]
Here's an interesting Django bug report covering something similar: https://code.djangoproject.com/ticket/29280

Maybe we modify `MyEntity._meta.db.transaction()` so you can specify which transaction type you want.

**Comment by sinisaos** [comment]
> 
> ```python
> await self.connection.execute("BEGIN IMMEDIATE")
> ```

This line solves the problem in my test case. No database lock and everything works fine. @dantownsend Well noted.

**Comment by dantownsend** [comment]
@sinisaos Hmm, strange.

What query are you running inside the transaction? Are you still also passing `timeout` to `SQLiteEngine`?

**Comment by sinisaos** [comment]
> What query are you running inside the transaction? Are you also passing `timeout` to `SQLiteEngine`?

It works :). I forgot to pass `timeout` to `SqliteEngine`. Sorry

**Comment by dantownsend** [comment]
@sinisaos OK, cool.

There's basically two things causing the locks:

1. If a transaction is open too long, which can happen with asyncio with lots of concurrent connections (passing in `timeout` helps with this)
2. If we use `BEGIN` instead of `BEGIN IMMEDIATE`, and the first query in the transaction is a `SELECT`, then SQLite turns it into a `read` transaction. If we then try and do something like an `INSERT` within the transaction, SQLite tries to upgrade it to a `write` transaction, but if several connections try doing this, we get the lock error.

The problem with `BEGIN IMMEDIATE` is it's less efficient is someone just wants to do `SELECT` queries in the transaction. So we will have to allow the user to specify which transaction type they want.

**Comment by powellnorma** [comment]
>  Does that fix things for you?

It looks like this was exactly the problem, I haven't seen the `database is locked` since - Thank you!

**Comment by dantownsend** [comment]
In the next version of Piccolo, this will be fixed.

https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_types/transactions.html?highlight=transaction#transaction-types

We've added transaction types for SQLite.

The current fix was to patch `SQLiteEngine` so it always used `BEGIN IMMEDIATE`. However, in the new version of Piccolo you'll have to explicitly tell it that you want an immediate transaction:

```python
from piccolo.engine.sqlite import TransactionType
async with Band._meta.db.transaction(transaction_type=TransactionType.immediate):
    ...
```

I haven't made `immediate` the default, to mirror the way SQLite behaves (which uses `deferred` by default).

**Comment by dantownsend** [comment]
I added a page to the docs too about how to use SQLite / asyncio / Piccolo together:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/tutorials/using_sqlite_and_asyncio_effectively.html
