### ISSUE TITLE
uniform behaviour on joining null values

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#690]
Lets say the artist is unknown (= null), and we have a query like this:
```
song = await Song.select(Song.artist.all_columns()).first()
```
When using SQLiteEngine, `song['artist']['id']` is `None`, but with PostgresEngine it seems that `song['artist']` is `None`. Can we make it so that SQLiteEngine behave like PostgresEngine in this regard?

**Comment by powellnorma** [comment]
This might be an false alarm, I have changed some code in piccolo which could be the reason for this discrepancy. So if you can't reproduce this, it is probably safe to close this

**Comment by sinisaos** [comment]
@powellnorma I'm sorry, but I can't reproduce your problem. The behavior of both engines is the same in my case (if  `Song.artist == None`) . If the query is 
```python
song = await Song.select(Song.artist.all_columns()).first()
print(song["artist"]) # KeyError: 'artist'
print(song["artist.id"]) # == None
```
you access dictionary keys like this `song["artist.id"]` and it's `None` both Sqlite and Postgres. 
If you want `song["artist"]` (which is also `None` in this case), you must also include the Song columns in a query like this
```python
song = await Song.select(
    Song.all_columns(), Song.artist.all_columns()
).first()
print(song["artist"]) # == None
print(song["artist.id"]) # == None
```
 Hope this helps.

**Comment by powellnorma** [comment]
My example was missing `.output(nested=True)` - But I just tested this with a "clean" piccolo, and this seems to be indeed not reproducible, so I will close this issue.

One thing I still wonder about though, is why we don't make it so that `song["artist"]` is None, instead of just (in case of nested output) `song["artist"]["id]`.
