### ISSUE TITLE
all_columns gets very slow ?

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#691]
When I add 50 items to my database every second, at first it takes 0.1s, then 0.7s 1.9s 3.9 5.3 ..195s(!)
CPU-Usage is also quite high (near 100% of single core). I have this problem with sqlite as well as postgres.

With py-spy i created a flame-graph of the process, and it looks like "all_columns()" somehow is very slow? Will do more testing, but just wanted to ask in case this rings a bell for someone.

Here a part of the flamegraph:

![grafik](https://user-images.githubusercontent.com/101364699/204636067-2b6f76ec-c83f-45c1-9d32-84000625ff35.png)

**Comment by powellnorma** [comment]
For the record, the line that is sampled so often is the following:
https://github.com/piccolo-orm/piccolo/blob/f3db5b3ac1dcb9bae22d7487ed92b3b7f693d74b/piccolo/columns/column_types.py#L2133

**Comment by powellnorma** [comment]
So when I remove that above try-except block, the performance issue is gone. However I am not sure what side-effects this has. What is the purpose of this `delattr` statement in that context? Thank you for your help

**Comment by dantownsend** [comment]
I've written this test script:

```python
import asyncio
import time

from piccolo.table import Table
from piccolo.engine.sqlite import SQLiteEngine
from piccolo.columns import Varchar


DB = SQLiteEngine()


class MyTable(Table, db=DB):
    name = Varchar()


async def main():
    await MyTable.create_table(if_not_exists=True)

    for _ in range(100):
        start = time.time()

        await MyTable.insert(
            *[MyTable(name=f'{start}_{i}') for i in range(50)]
        )

        end = time.time()
        print(f'Time taken: {end - start}')


if __name__ == '__main__':
    asyncio.run(main())
```

In this simple example, the insert performance seems to be consistent. But there could be some edge case we need to look at.

The `delattr` exists because of the way foreign keys work in Piccolo:

```python
class Manager(Table):
    name = Varchar()

class Band(Table):
    manager = ForeignKey(Manager)

# When we access 'manager' it adds / remove attributes to a copy of itself for a fluent interface:
Band.manager.name
```

We may be able to optimise it a bit. I commented out this:

https://github.com/piccolo-orm/piccolo/blob/f3db5b3ac1dcb9bae22d7487ed92b3b7f693d74b/piccolo/columns/column_types.py#L2131-L2135

And all of the tests still passed.

**Comment by dantownsend** [comment]
What kind of insert query were you doing? Just so I can try the test script again with your query.

**Comment by powellnorma** [comment]
My initial issue description was a bit missleading, as I think it's not the insert that is slow, but the select (which happens right after having inserted the new item(s)). That select query uses `all_columns`, and as shown by the flamegraph that function takes a lot of time. So it something looks like this:
```python
async with Item._meta.db.transaction():
    ret = []
    for data in list:
        await add_item_data(data)
        loaded_item = await load_item(data['id'])  # load_item uses queries like `Item.select(Item.all_columns())`
        ret.append(loaded_item)
```

While the load_item probably could be moved out of the transaction, I think there is still a performance issue with `all_colums`. Because like I mentioned, when I just remove that said `delattr` section, I don't have this performance issue any longer.

I will see if I can provide code that reproduces this issue later!

**Comment by sinisaos** [comment]
@dantownsend I modified your script and I added a table with one FK column and can confirm that the results are consistent. Test script:
```python
import asyncio
import time

from piccolo.table import Table
from piccolo.engine.sqlite import SQLiteEngine
from piccolo.columns import Varchar, ForeignKey


DB = SQLiteEngine()


class MyTable(Table, db=DB):
    name = Varchar()


class MyFKTable(Table, db=DB):
    name = Varchar()
    fk = ForeignKey(MyTable)


async def main():
    await MyTable.create_table(if_not_exists=True)
    await MyFKTable.create_table(if_not_exists=True)

    for _ in range(50):
        start = time.time()

        await MyTable.insert(
            *[MyTable(name=f"{start}_{i}") for i in range(1000)]
        )

        await MyFKTable.insert(
            *[MyFKTable(name=f"{start}_{i}", fk=1) for i in range(1000)]
        )

        end = time.time()
        print(f"Insert time taken: {end - start}")

        s = time.time()
        data = await MyFKTable.select(
            MyFKTable.all_columns(), MyFKTable.fk.all_columns()
        )
        e = time.time()
        print(f"Query time taken for {len(data)} records: {e - s}")


if __name__ == "__main__":
    asyncio.run(main())
```
Result is:
```
Insert time taken: 0.17480182647705078
Query time taken for 50000 records: 0.34092068672180176
```
I will try adding more foreign keys to the table and see how it behaves. It would be best if @powellnorma can show the code that is problematic so we can investigate further.

**Comment by powellnorma** [comment]
Ok, so here is some code that reproduces the issue. Please note the following:
* When trying it with sqlite, the patch from https://github.com/piccolo-orm/piccolo/issues/687#issuecomment-1328135364 probably should be applied first
* The time `add_new_to_list` takes increases steadily, and reaches well above 10s. But when one comments out the `delattr` loop, it stays at at < 0.5s

```python
import asyncio
from time import time

from piccolo.columns.column_types import Varchar, ForeignKey
from piccolo.engine.sqlite import SQLiteEngine
from piccolo.table import Table
from starlette.applications import Starlette
import uvicorn

DB = SQLiteEngine('data.db', timeout=300)

class EntityASubA(Table, db=DB):
    property_1 = Varchar(null=True)
    property_2 = Varchar(null=True)
    property_3 = Varchar(null=True)

class EntityASubBSubA(Table, db=DB):
    property_1 = Varchar(null=True)
    property_2 = Varchar(null=True)
    property_3 = Varchar(null=True)

class EntityASubB(Table, db=DB):
    property_1 = Varchar(null=True)
    property_2 = Varchar(null=True)
    property_3 = Varchar(null=True)
    foreign_1 = ForeignKey(EntityASubA, null=True)
    foreign_2 = ForeignKey(EntityASubA, null=True)

class EntityA(Table, db=DB):
    key = Varchar(unique=True)
    property_1 = Varchar(null=True)
    property_2 = Varchar(null=True)
    property_3 = Varchar(null=True)
    property_4 = Varchar(null=True)
    property_5 = Varchar(null=True)
    property_6 = Varchar(null=True)
    property_7 = Varchar(null=True)
    foreign_1 = ForeignKey(EntityASubA, null=True)
    foreign_2 = ForeignKey(EntityASubA, null=True)
    foreign_3 = ForeignKey(EntityASubB, null=True)
    foreign_4 = ForeignKey(EntityASubB, null=True)

class Main(Table, db=DB):
    key = Varchar(unique=True)
    property_1 = Varchar(null=True)
    property_2 = Varchar(null=True)
    property_3 = Varchar(null=True)
    property_4 = Varchar(null=True)
    foreign_1 = ForeignKey(EntityA, null=True)
    foreign_2 = ForeignKey(EntityA, null=True)

async def add_main(i):
    m = await Main.objects().get_or_create(Main.key == f"Main-{i}")
    a = await EntityA.objects().get_or_create(EntityA.key == f"EntityA-{i}")
    m.foreign_1 = a
    await m.save()

async def load_main(i):
    return await Main.select(
        Main.all_columns(),
        Main.foreign_1.all_columns(),
        Main.foreign_2.all_columns(),
    ).where(Main.key == f"Main-{i}").output(nested=True).first()

async def add_new_to_list():
    ret = []
    async with Main._meta.db.transaction():
        for i in range(100):
            await add_main(i)
            ret.append(await load_main(i))
    return ret

async def measure_add_new_list(i):
    t_start = time()
    print(f"add_new_to_list-{i}: started ..")
    await add_new_to_list()
    print(f"add_new_to_list-{i}: took {round(time() - t_start, 3)}s")

async def on_startup2():
    for i in range(50):
        asyncio.create_task(measure_add_new_list(i))
        await asyncio.sleep(1)

async def on_startup():
    asyncio.create_task(on_startup2())

app = Starlette(debug=True, on_startup=[on_startup])
import os
print("pid:", os.getpid())

if __name__ == '__main__':
    EntityASubA.create_table(if_not_exists=True).run_sync()
    EntityASubBSubA.create_table(if_not_exists=True).run_sync()
    EntityASubB.create_table(if_not_exists=True).run_sync()
    EntityA.create_table(if_not_exists=True).run_sync()
    Main.create_table(if_not_exists=True).run_sync()

    uvicorn.run(app, host='127.0.0.1', port=64215)
```

**Comment by sinisaos** [comment]
> * The time `add_list` takes increases steadily, and reaches well above 10s. But when one comments out the `delattr` loop, it stays at at < 0.5s

I tried your code example and indeed if I remove [this code](https://github.com/piccolo-orm/piccolo/blob/f3db5b3ac1dcb9bae22d7487ed92b3b7f693d74b/piccolo/columns/column_types.py#L2131-L2135) everything works fine and the results are consistent. Maybe we should remove that from the code and as @dantownsend  wrote, all tests pass, but need to be double-checked for unwanted implications.

**Comment by dantownsend** [comment]
@powellnorma Thanks for posting this example, and @sinisaos for giving it a go.

I need to investigate what's going on.

**Comment by sinisaos** [comment]
@dantownsend I don't know if you've had time to look into this, and I've been playing around with this and I think we could safely remove [this piece of code](https://github.com/piccolo-orm/piccolo/blob/f3db5b3ac1dcb9bae22d7487ed92b3b7f693d74b/piccolo/columns/column_types.py#L2131-L2135) because that code does nothing but slow things down also in `GET` requests. 
```
~$ bombardier -c 200 -d 10s -l http://localhost:8000
Bombarding http://localhost:8000 for 10s using 200 connection(s)
[==========================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec        13.15      98.93    1048.77
  Latency         6.97s      4.61s     11.05s
  Latency Distribution
     50%     10.00s
     75%     11.02s
     90%     11.03s
     95%     11.03s
     99%     11.04s
  HTTP codes:
    1xx - 0, 2xx - 130, 3xx - 0, 4xx - 0, 5xx - 0
    others - 200
  Errors:
    the server closed connection before returning the first response byte. Make sure the server returns 'Connection: close' response header before closing the connection - 200
  Throughput:     9.54KB/s
```
If we have a nesting `fk` less than `2` (eg `Band.manager.id`, this code is not triggered), but if we remove `except` statement from the loop, and the nesting is deeper than `2` (eg `Concert.band_1.manager.id`) `delattr()` raise `AttributeError`. If we remove that code, result is
```
~$ bombardier -c 200 -d 10s -l http://localhost:8000
Bombarding http://localhost:8000 for 10s using 200 connection(s)
[==========================================================================] 10s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec       202.16     309.01    1349.00
  Latency         0.92s    95.55ms      1.42s
  Latency Distribution
     50%      0.92s
     75%      0.96s
     90%      1.00s
     95%      1.05s
     99%      1.22s
  HTTP codes:
    1xx - 0, 2xx - 2207, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:   105.77KB/s
```
which is decent for deeply nested queries with only one `Unicorn` worker and without `Gunicorn`.

**Comment by dantownsend** [comment]
@sinisaos Thanks for investigating it. So you think that if we remove it entirely, there's no negative effects, even for deeply nested queries?

**Comment by sinisaos** [comment]
@dantownsend Yes, you can try this sample schema and query.
```python
DB = SQLiteEngine()

class Manager(Table, db=DB):
    name = Varchar(length=100)

    @classmethod
    def get_readable(cls) -> Readable:
        return Readable(template="%s", columns=[cls.name])


class Band(Table, db=DB):
    name = Varchar(length=100)
    manager = ForeignKey(references=Manager)

    @classmethod
    def get_readable(cls) -> Readable:
        return Readable(template="%s", columns=[cls.name])


class Concert(Table, db=DB):
    band_1 = ForeignKey(references=Band)
    band_2 = ForeignKey(references=Band)


class Tour(Table, db=DB):
    tour_1 = ForeignKey(references=Concert)
    tour_2 = ForeignKey(references=Concert)

#FastAPI route
@app.get("/")
async def root() -> JSONResponse:
    data = await Tour.select(
        Tour.all_columns(),
        Tour.tour_1.band_1.id,
        Tour.tour_1.band_1.name,
        Tour.tour_1.band_1.manager.id,
        Tour.tour_1.band_1.manager.name,
        Tour.tour_2.band_2.id,
        Tour.tour_2.band_2.name,
        Tour.tour_2.band_2.manager.id,
        Tour.tour_2.band_2.manager.name,
    ).output(nested=True)

    return JSONResponse({"data": data})
```
I didn't try to go deeper, but I think even deeper would be fine (if it makes sense to go deeper). If we don't remove that [for loop](https://github.com/piccolo-orm/piccolo/blob/f3db5b3ac1dcb9bae22d7487ed92b3b7f693d74b/piccolo/columns/column_types.py#L2131-L2135), I can't even start `bombardier` to make a test because everything is frozen, but without that code everything is fine.

**Comment by dantownsend** [comment]
@sinisaos Thanks - that test script is helpful.

**Comment by dantownsend** [comment]
OK, I see what the problem is now. I think I have a fix, but need to write some tests.

**Comment by dantownsend** [comment]
I've opened a PR with a fix.

It's quite hard to explain what the problem was - but basically the `foreign_key_meta.proxy_columns` list kept on growing, so over time the number of calls to `delattr` was increasing.

This seems to solve the problem for me, but if you could also check it fixes things for you that would be great.

**Comment by sinisaos** [comment]
> It's quite hard to explain what the problem was - but basically the `foreign_key_meta.proxy_columns` list kept on growing, so over time the number of calls to `delattr` was increasing.

Yes, that's exactly the problem and with your changes it disappeared. `Bombardier` results are the same if we delete the for loop or if add your changes :thumbsup:.

**Comment by dantownsend** [comment]
@sinisaos Thanks for checking it.

I've written tests for it now, and think it's good to go - will release it later today.

**Comment by dantownsend** [comment]
@powellnorma @sinisaos Thanks for your help - this was a tricky one.
