### ISSUE TITLE
Getting number of affected rows

### ISSUE THREAD

**Issue by waldner** [piccolo-orm/piccolo#698]
With some operations, postgres returns the number of affected/processed rows. Other ORMs make that information available. My use case is for deletions, but perhaps it would be nice to have this in general.
I haven't looked at the codebase, but how hard would that be to implement? I might give that a try if it's not too complicated.

**Comment by dantownsend** [comment]
Good idea - we should add this.

Currently we have a [returning clause](https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_clauses/returning.html) for insert and delete queries.

Maybe if we just implement this for delete, it will kill two birds with one stone.

```python
# We can get the number of deleted rows:
>>> len(await Band.delete().where(Band.popularity < 100).returning(Band.id))
3

# But also useful for other things:
>>> await Band.delete().where(Band.popularity < 100).returning(Band.name)
[{'name': 'Band 1'}, {'name': 'Band 2'}]
```

If you look at how we do it for `update` queries, it's fairly straightforward.

It needs a `returning` method, which basically just passed data to the `ReturningDelegate`:

https://github.com/piccolo-orm/piccolo/blob/1f036ad37fc5290412809988537dc606bbaf3cf6/piccolo/query/methods/update.py#L55-L57

And then the querystring is modified:

https://github.com/piccolo-orm/piccolo/blob/1f036ad37fc5290412809988537dc606bbaf3cf6/piccolo/query/methods/update.py#L105-L110

So we would have to do something similar here for `delete` queries:

https://github.com/piccolo-orm/piccolo/blob/1f036ad37fc5290412809988537dc606bbaf3cf6/piccolo/query/methods/delete.py#L44-L51

If you want to give it a go, that would be great.

**Comment by waldner** [comment]
I think the returning clause is for inserts and updates, so what you suggest to extend it to deletions makes sense.
Thanks for the pointer; since I'll be doing this in my spare time (which is not much), don't hold your breath. But I'll check that out ASAP.

**Comment by dantownsend** [comment]
Cool, thanks! No pressure.
