### ISSUE TITLE
Modify app template to use `table_finder`

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#706]
When using `piccolo app new my_app` to create a new Piccolo app, the `piccolo_app.py` file generated doesn't use `table_finder` (note below how `table_classes=[]`).

https://github.com/piccolo-orm/piccolo/blob/eb6ba32e85c2357969e0131a2991b7e50a1dcfb1/piccolo/apps/app/commands/templates/piccolo_app.py.jinja#L14-L20

If you look at what we do with the `piccolo asgi new command`:

https://github.com/piccolo-orm/piccolo/blob/eb6ba32e85c2357969e0131a2991b7e50a1dcfb1/piccolo/apps/asgi/commands/templates/app/home/piccolo_app.py.jinja#L14-L22

Note how `table_classes=table_finder(modules=["home.tables"], exclude_imported=True)`.

Using `table_finder` is easier, as it means you don't have to manually register the tables for migrations to work. Sometimes people might want to do it manually, but doing it automatic is preferred in most situations.

**Comment by mehakkalra14** [comment]
Hi, can I work on this? It is a bit urgent

**Comment by dantownsend** [comment]
@mehakkalra14 Of course - feel free to pick this up. Thanks!
