### ISSUE TITLE
asyncpg.exceptions.UndefinedFunctionError: Operator existiert nicht: json = unknown

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#713]
So I have a model like this, with a JSON column:
```python
class Main(Table):
    extraAttribtues = JSON(null=True)
```
Now when I do `Main.objects().get_or_create(Main.extraAttribtues == my_attrs)` I get the exception:
```
asyncpg.exceptions.UndefinedFunctionError: Operator existiert nicht: json = unknown
```

I have looked it up, and it seems that it stems from the fact that postgres refuses to compare json: https://dba.stackexchange.com/a/106290 - Is there a workaround I could use in this case? Or maybe we could make piccolo compare `jsonb` in these cases? Thank you four your help.

**Comment by powellnorma** [comment]
Ok nvm - Just found out about the `JSONB` Column Type!

**Comment by dantownsend** [comment]
Yeah, the `JSONB` column is generally more powerful.

It looks like we can compare JSON fields, but we first have to cast them to JSONB.

```sql
select * from my_table where my_json_column::jsonb = '{"message": "hello"}'::jsonb;
```

Maybe it's something we'll add to Piccolo at some point, so the JSON columns are more useful.
