### ISSUE TITLE
Join via primary key

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#727]
Let's say I have

```python
class Band(Table):
    id = Integer(primary_key=True)
    name = Varchar()

class BandExtra(Table):
    id = Integer(primary_key=True)
    extra_info = Varchar()
```

Hwo can I select `BandExtra.extra_info` from a `Band.select` within a single query? I know I could add an additional `ForeignKey` to the `Band` Table, but if possible I would like to avoid additional columns. Is there a way? Thank you

**Comment by dantownsend** [comment]
So you're assuming that the ID for each table will be the same, and you'll link them together that way instead of an explicit foreign key?

Hmm, that's a bit tricky currently with Piccolo, because we abstract away joins from the user. We would have to expose an API for the user to specify joins manually.

Probably the best bet is two queries, and splicing the data together in Python.

```python
async def my_func():
    band = await Band.select().first()
    band_extra = await BandExtra.select(BandExtra.extra_info).where(BandExtra.id == band['id']).first()
    return {**band, **band_extra)
```

**Comment by powellnorma** [comment]
Yes, that is what I am doing currently. But it seems like every additional query adds a bit of overhead, which is why I try to avoid it. However by wrapping the different queries in a `async with DB.transaction()` it looks like I am able to reduce this overhead.

Maybe in the future we could do/add something like:

```python
class Band(Table):
    id = Integer(primary_key=True)
    name = Varchar()
    extra = ReverseLookup(LazyTableReference("BandExtra", module_path=__name__), "id", first=True)

class BandExtra(Table):
    id = Integer(primary_key=True)
    extra_info = Varchar()
```
The `first=True` would limit the select in the subquery

**Comment by powellnorma** [comment]
@dantownsend 

What do you think about an API like this?
```python
class BandExtra(Table):
    id = ForeignKey(Band, primary_key=True)
```

**Comment by dantownsend** [comment]
Hey - sorry for the slow reply, I caught the flu over the holidays.

> `id = ForeignKey(Band, primary_key=True)`

Yeah, that could work. I haven't tried having a column be a primary key and foreign key, but there doesn't seem to be a reason we couldn't do it.

I had this idea for us supporting arbitrary joins between tables, without foreign keys - what do you think?

```python
class Band(Table):
    id = Integer(primary_key=True)
    name = Varchar()
    extra = Join('BandExtra', from='id', to='id')  # <- This

class BandExtra(Table):
    id = Integer(primary_key=True)
    extra_info = Varchar()
```

We could keep Piccolo's fluent interface for joins.

```python
await Band.select(Band.name, Band.extra.extra_info.as_alias('extra_info'))
```

Just an idea.

**Comment by dantownsend** [comment]
OK, I have a solution for this now:

https://github.com/piccolo-orm/piccolo/pull/782

It allows joins without having to specify a foreign key first.

**Comment by dantownsend** [comment]
For your example:

```python
class Band(Table):
    id = Integer(primary_key=True)
    name = Varchar()

class BandExtra(Table):
    id = Integer(primary_key=True)
    extra_info = Varchar()

# This query will now work:
await Band.select(Band.name, Band.id.join_on(BandExtra.id).extra_info.as_alias('extra_info'))
```
