### ISSUE TITLE
Page admin is not displayed in https mode, but in http it work well

### ISSUE THREAD

**Issue by Edw125** [piccolo-orm/piccolo#763]
Hello. I want to build service that includes piccolo admin. Basically everything is great, but I installed the certificates SSL on my dev server and I ran into a problem. I have the following components: nginx, fastapi, piccolo orm and admin. When I try to open the site in dev mode with using ssl I get page without static like this 
![image](https://user-images.githubusercontent.com/57034089/218340047-f4be0de2-a253-4cc3-be42-af3ebaf8eff0.png)
in logs I see what subrequests are sent with 404 code
![image](https://user-images.githubusercontent.com/57034089/218340064-a0bcc7e3-447b-427e-b345-36d655c97631.png)
I understood that static files such as html css js are located in folder venv/lib/...., but in docker I didn't find it. Maybe need configure in any way nginx to serve static?

How to solve this? Thanks for answers

**Comment by dantownsend** [comment]
Piccolo Admin serves its own static files, so you shouldn't have to worry about that.

`create_admin` has an argument called `allowed_hosts` which adds extra security when running under HTTPS:

https://piccolo-admin.readthedocs.io/en/latest/asgi/index.html#source

Try setting that to `['telegram-access.ddns.net']`.

```python
create_admin(..., allowed_hosts=['telegram-access.ddns.net'])
```

**Comment by Edw125** [comment]
I already tried that
![image](https://user-images.githubusercontent.com/57034089/218455367-02d96d99-623c-4109-a4bd-0149cee00c8e.png)
but I think the problem in nginx
![image](https://user-images.githubusercontent.com/57034089/218455668-d03c6f58-745e-4ce4-858c-179cd302b0c5.png)

**Comment by Edw125** [comment]
This is work. Thanks! )
