### ISSUE TITLE
Q: Can you dynamically set the engine associated with a table?

### ISSUE THREAD

**Issue by eddyg** [piccolo-orm/piccolo#790]
Is it possible to "late bind" the database for tables in Piccolo?

The examples I've found either do something like shown below, or rely on a `piccolo_conf.py` file:

```python
DB = SQLiteEngine("todo.db")

class Todo(Table, db=DB):
    ...
```

I'd like to keep the database stuff "localized". For example, here's some pseudo code based on an existing app that has add-on modules. It is currently using `aiosqlite` directly with raw SQL queries. I'd like to try and convert it to use Piccolo, and keep all the database stuff defined in the module, like it is now:

```python
class Todo(Table):
    title = Text()
    completed = Boolean()

class TodoHandler(Addon):
    def __init__(self):
        if not db_location := self.settings.get("TODO_DATABASE_FILE"):
            raise ValueError("Todo database location not defined")

        self.db = SQLiteEngine(path=db_location)

        # ••• do something here to "bind" the 'Todo' table to 'self.db' •••

        Todo().create_table(if_not_exists=True).run_sync()
```

Is something like this possible?

**Comment by dantownsend** [comment]
Yes, you can assign the DB to a Piccolo table at any time. We do something like this when testing Piccolo Admin:

https://github.com/piccolo-orm/piccolo_admin/blob/9306373cc7ac6f7058d41379023bebe1c3560341/piccolo_admin/example.py#L415-L423

So you just need to assign to `MyTable._meta.db`.

**Comment by eddyg** [comment]
A-ha! Thanks for the pointer to `_meta`. 🎉

This looks exactly like what I was looking for. (Almost seems like it might be worthwhile to expose this capability as a public method to make it more obvious.)

Thanks again. I very much appreciate your time. Not only to reply, but also that you put into the Piccolo project!
