### ISSUE TITLE
Q: "INSERT OR REPLACE" or "ON CONFLICT" (a.k.a. conflict resolution) support?

### ISSUE THREAD

**Issue by eddyg** [piccolo-orm/piccolo#791]
Does Piccolo have a way to do "INSERT OR REPLACE" or "ON CONFLICT" queries to handle conflict resolution?

From the SQLite docs on [INSERT](https://www.sqlite.org/lang_insert.html):

> The initial "INSERT" keyword can be replaced by "REPLACE" or "INSERT OR _action_" to specify an alternative constraint [conflict resolution algorithm](https://www.sqlite.org/lang_conflict.html) to use during that one INSERT command. For compatibility with MySQL, the parser allows the use of the single keyword [REPLACE](https://www.sqlite.org/lang_replace.html) as an alias for "INSERT OR REPLACE".

INSERT's "upsert clause" is another alternative where you can specify what columns to update with more granularity if a row already exists.

**Comment by dantownsend** [comment]
Someone started work on an `ON CONFLICT` clause, but it stalled out.

https://github.com/piccolo-orm/piccolo/issues/252

It has been requested a few times recently, so will try and add it soon - should be quite a simple feature to add.

**Comment by eddyg** [comment]
Great to hear. Looking forwarding to it. Thanks again!

Also, I didn't realize Discussions were available for this project. A search eventually landed me [here](https://github.com/piccolo-orm/piccolo/discussions/248). I'll avoid opening issues for questions in the future!
