### ISSUE TITLE
`asyncpg.pgproto.pgproto.UUID` is incompatible with `uuid.UUID`

### ISSUE THREAD

**Issue by lqmanh** [piccolo-orm/piccolo#797]
Hi, I'm having this problem when serializing query results with Pydantic.
Piccolo returns `piccolo.columns.UUID` columns as `asyncpg.pgproto.pgproto.UUID` objects, which seems not to play well with stdlib `uuid.UUID`. As a result Pydantic can't serialize fields annotated with `uuid.UUID` correctly.

Is there some way to make Piccolo return UUID columns as standard `uuid.UUID` values instead?

Thanks in advance!

**Comment by dantownsend** [comment]
@lqmanh What does your Pydantic model look like?

I did a quick test locally and this seems to work:

```python
from piccolo.columns import UUID

class MyTable(Table):
    my_column = UUID()

class MyModel(BaseModel):
    code: uuid.UUID

rows = await MyTable.select()
[MyModel(**i) for i in rows]
```

Is the problem with loading data into a Pydantic model, or outputting from a Pydantic model to JSON?

**Comment by dantownsend** [comment]
@lqmanh One solution is to have a custom Pydantic config like this, which tells Pydantic how to handle these values.

We do this with `create_pydantic_model`:

https://github.com/piccolo-orm/piccolo/blob/56669fab0cc6626ccc7be707b094a022b9a0ba36/piccolo/utils/pydantic.py#L27-L37

**Comment by lqmanh** [comment]
@dantownsend I've rechecked and looks like it only happens when using with Starlite. Manual serialization like above seems fine. Thanks for quick response!
