### ISSUE TITLE
UndefinedTableError in SQL for ORM query with explicit DB schema (postgres)

### ISSUE THREAD

**Issue by Richard-Otterli** [piccolo-orm/piccolo#817]
When trying to use the ORM I run in to an issue when running the `Table.objects()` or `Table.select()` queries.

I loaded an existing database and ran the migrations successfully, as per the instructions.

The piccolo app 'feeds' has a `tables.py` containing a table called 'product_sources'. This table is in a DB schema named 'feeds'.

**Table class**

```
class ProductSources(Table, tablename="feeds.product_sources"):
    id = Serial(
        null=False,
        primary_key=True,
        unique=False,
        index=True,
        index_method=IndexMethod.btree,
        db_column_name=None,
        secret=False,
    )
    name = Varchar(
        length=125,
        default="",
        null=True,
        primary_key=False,
        unique=True,
        index=True,
        index_method=IndexMethod.btree,
        db_column_name=None,
        secret=False,
    )
```

Generating the piccolo schema and migrations went fine. However now trying to run a basic query with the ORM is running in to issues.

**Script**
```
from feeds.tables import ProductSources

def get_sources():
    return ProductSources.select(ProductSources.id).run_sync()

if __name__ == '__main__':
    get_sources()
```

**Error received**: `asyncpg.exceptions.UndefinedTableError: missing FROM-clause entry for table "feeds.product_sources"`

After digging a bit deeper it looks like the SQL query it tries to execute is wrong. 

**SQL query**: `SELECT ALL "feeds.product_sources"."id" FROM feeds.product_sources`

When executing directly with SQL - it gives the same error as above "missing FROM-clause...". 

It looks like the double-quotes around the table ref in column variables is causing issues. 

Removing the quotes fixes the query.

i.e. `SELECT ALL feeds.product_sources."id" FROM feeds.product_sources`

### Question: 
Am I executing this correctly for an explicit DB schema table query? Could this be a bug?

**Piccolo Versions**
piccolo                 0.110.0
piccolo-admin      0.48.0
piccolo-api           0.54.0

**Postgres version** 14.2

**Comment by sinisaos** [comment]
@Richard-Otterli I can't reproduce your problem because I didn't generate the tables from the existing schema, but if I try to create a new schema, the error is already in the migrations. I think the problem is here.  
> ```
> class ProductSources(Table, tablename="feeds.product_sources"):
> ```
It should be 
```python
class ProductSources(Table, tablename="product_sources"):
 ```
because you don't need to specify piccolo app name in `tablename` [argument](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/defining.html#tablename). If I change that line everything works. Can you try that and see if it works? Sorry if that doesn't help.

**Comment by dantownsend** [comment]
Yes, this looks like a problem with using Postgres schemas.

We don't have a lot of test coverage on this, so it looks like a bug.

@Richard-Otterli You're right - this is the problem.

> SQL query: SELECT ALL "feeds.product_sources"."id" FROM feeds.product_sources

We quote the tablename, in case it clashes with a Postgres keyword. But then Postgres thinks the tablename is called `feed.product_sources`, rather than `product_sources` in a schema called `feed`.

So we probably need to so something like this:

```
"feeds"."product_sources"
```

**Comment by Richard-Otterli** [comment]
Ah cool - thought that might be the case (with the double quotes). Thanks for looking at this @dantownsend.

I'm quite new to the Github public community - what are the next steps to having this resolved? I appreciate there's a lot to do in the PRs already but this also seems like a blocker for anyone with the same issue.

**Comment by Richard-Otterli** [comment]
> @Richard-Otterli I can't reproduce your problem because I didn't generate the tables from the existing schema, but if I try to create a new schema, the error is already in the migrations. I think the problem is here.
> 
> > ```
> > class ProductSources(Table, tablename="feeds.product_sources"):
> > ```
> 
> It should be
> 
> ```python
> class ProductSources(Table, tablename="product_sources"):
> ```
> 
> because you don't need to specify piccolo app name in `tablename` [argument](https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/defining.html#tablename). If I change that line everything works. Can you try that and see if it works? Sorry if that doesn't help.

Thanks for taking the time to help@sinisaos. However I believe the table class would only query to the default `public` schema, as the schema is not explicitly define in the `tablename` argument.

Maybe an option would be to have a "schema" parameter for the table class?

**Comment by dantownsend** [comment]
@Richard-Otterli We're just finishing up a PR for upsets, after that I'll have a look at this.

**Comment by dantownsend** [comment]
> Maybe an option would be to have a "schema" parameter for the table class?

Yes, that's what we need to do.

**Comment by Richard-Otterli** [comment]
Thank you for this improvement @dantownsend !

**Comment by dantownsend** [comment]
@Richard-Otterli No worries. I'll release it soon.

After merging it in I realised there was a use case I hadn't considered.

With Piccolo's auto migrations, if we have this table:

```python
class Band(Table):
    ...
```

And we change it to this:

```python
class Band(Table, schema="music"):
    ...
```

Then it will detect that the schema has changed, and will move the table to the `"music"` schema.

The thing I haven't accounted for currently is having multiple tables with the same table name, but in different schemas.

```python
class Band(Table, tablename="band", schema="music"):
    ...

class Band2(Table, tablename="band", schema="music_2"):
    ...
```

This might confuse the auto migration system. I need to do a bit of testing before releasing it, just in case.

**Comment by dantownsend** [comment]
OK, this is live now in `piccolo==0.112.0`.

**Comment by Richard-Otterli** [comment]
Amazing! This  game changer and is especially helpful in reading existing databases. Haven't found it in any other async framework, so looking forward to trying it out. Thanks again 🙌 @dantownsend
