### ISSUE TITLE
Qustion about guarantee of execution order

### ISSUE THREAD

**Issue by powellnorma** [piccolo-orm/piccolo#839]
Hi, just to be sure, the following code is guaranteed to insert the rows correctly, right? 

```python
# assume `new_bs` is not empty

await AtoB.delete().where(AtoB.a == a_id)
for b_id in new_bs:
    await AtoB.objects().get_or_create((AtoB.a == a_id) & (AtoB.b == b_id))
await A.update(bs_last_updated=now()).where(A.id == a_id)

rows = await AtoB.get().where(AtoB.a == a_id)
assert rows  # guaranteed to not throw ?
```

Or is there a chance that perhaps `get_or_create` thinks the row still exist, and does not create a new one?

Background: I tried to understand why for a specific `a_id` no rows were stored, even though the `bs_last_updated` was set to some days ago. While it is possible that `new_bs` was empty, it is rather unlikely (but not impossible).

And if the code was racy, is the following improvement safe?

```python
for b_id in new_bs:
    await AtoB(a=a_id, b=b_id).save()
```

Thank you for your help!

**Comment by dantownsend** [comment]
What you've done should work OK.

`get_or_create` should work fine with `and` (i.e. `get_or_create((AtoB.a == a_id) & (AtoB.b == b_id))`):

https://github.com/piccolo-orm/piccolo/blob/cd5595c08d94dcf048f30ae68812379e9bb0d992/piccolo/query/methods/objects.py#L75

The only situation where you might get weirdness is if running this function multiple times in parallel. You could wrap it all in a transaction to be safe.

For this use case, you may also be able to use upserts instead - we recently added the `on_conflict` clause:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/query_clauses/on_conflict.html#on-conflict
