### ISSUE TITLE
Add a `pretty` option when dumping fixtures

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo#847]
When we dump fixtures:

```
piccolo fixtures dump my_app
```

It prints out the JSON, but it isn't formatted nicely. It would be good to have a `pretty` option:

```
piccolo fixtures dump my_app --pretty
```

Here's the relevant code:

https://github.com/piccolo-orm/piccolo/blob/74ea10d427464b05d4a0caba05ce317582d74203/piccolo/apps/fixtures/commands/dump.py#L111-L128

The simplest solution is to replace this line:

https://github.com/piccolo-orm/piccolo/blob/74ea10d427464b05d4a0caba05ce317582d74203/piccolo/apps/fixtures/commands/dump.py#L128

With this:

```python
if pretty:
    print(json.dumps(json.loads(json_string), indent=4))
else:
    print(json_string)
```

Though there may be a better way of doing it. We use Pydantic to create the JSON string, and there may be a way of getting it to do a pretty output, but I'm not sure.

**Comment by sinisaos** [comment]
@dantownsend Why don't we just use `indent` kwarg of [Pydantic model.json()](https://docs.pydantic.dev/latest/usage/exporting_models/#modeljson) and change this https://github.com/piccolo-orm/piccolo/blob/74ea10d427464b05d4a0caba05ce317582d74203/piccolo/apps/fixtures/commands/dump.py#L65 to this 
```python
return pydantic_model(**dump).json(indent=4)
```
so we always have nicely formatted json in output.

**Comment by dantownsend** [comment]
@sinisaos Cool, I was hoping it was possible with Pydantic - that's a much better solution.

**Comment by sinisaos** [comment]
@dantownsend If you want I can do a quick PR with this single line change.

**Comment by dantownsend** [comment]
@sinisaos I think the only question is ... do we make it the default behaviour, or is there value in making it configurable via a 'pretty' parameter?

**Comment by sinisaos** [comment]
@dantownsend I think that should be the default behavior just like we have all other things nicely formatted (like migrations etc) but as you wish. If you want to add the `--pretty` option, can you please do the PR instead of me, if not I can do that?

**Comment by dantownsend** [comment]
@sinisaos OK, I think you're right - I can't think of a great reason why you'd want the JSON without the nice formatting ... if that is a valid use case in the future, we'll add the ability to turn off the pretty formatting (i.e. `--pretty=True` by default).

If you can create a PR that would be great - thanks.

**Comment by dantownsend** [comment]
Resolved by https://github.com/piccolo-orm/piccolo/pull/848
