### ISSUE TITLE
Running migrations programmatically

### ISSUE THREAD

**Issue by Fingel** [piccolo-orm/piccolo#85]
Hello,

Is there a recommended way to run migrations programmatically, for example, when setting up a test suite?

It is possible to import `fowards` from https://github.com/piccolo-orm/piccolo/blob/master/piccolo/apps/migrations/commands/forwards.py#L83 but the code uses `sys.exit(0)` which kills the parent process. 

I suppose one could shell out the command as part of setting up the test environment, but I don't think that is ideal.

**Comment by dantownsend** [comment]
@Fingel You make a good point about `sys.exit` - I'll refactor it, so it can be run programatically.

**Comment by Fingel** [comment]
I found that it's possible to catch the `SystemExit` exception which makes it technically possible to run `forwards` and `backwards` within python. For example, as a pytest fixture to run and reverse migrations before/after running tests:

```python
@pytest.fixture(scope='session', autouse=True)
async def run_migrations():
    try:
        print('Running Migrations')
        await forwards(app_name='all')
    except SystemExit:
        pass

    yield

    try:
        print('Reversing Migrations')
        await backwards(app_name='all', migration_id=0, auto_agree=True)
    except SystemExit:
        pass
```

**Comment by dantownsend** [comment]
I refactored the migrations slightly, so you can run them without getting `SystemExit`.

```python
from piccolo.apps.migrations.commands.forwards import run_forwards
await run_forwards(app_name='all')

from piccolo.apps.migrations.commands.backwards import run_backwards
await run_backwards(app_name='all', migration_id=0, auto_agree=True)
```

Thanks for that code snippet - I need to document unit testing better at some point.

**Comment by Fingel** [comment]
Works great!
