### ISSUE TITLE
Something like «makemigrations»

### ISSUE THREAD

**Issue by hoosnick** [piccolo-orm/piccolo#862]
### Discussed in https://github.com/piccolo-orm/piccolo/discussions/861

<div type='discussions-op-text'>

<sup>Originally posted by **hoosnick** July 13, 2023</sup>
How can we implement the `makemigrations` command like in [Django](https://docs.djangoproject.com/en/4.2/ref/django-admin/#django-admin-makemigrations)? 
Why is it not implemented? It is not convenient to manually create migrations for each application and then migrate.</div>

**Comment by dantownsend** [comment]
This is the Piccolo equivalent:

```
piccolo migrations new my_app --auto
```

As mentioned in the discussion, we should reorder the [docs](https://piccolo-orm.readthedocs.io/en/latest/piccolo/migrations/create.html#auto-migrations), so this appears nearer the top of the page, as mention manual migrations first, which is a less common use case.

**Comment by hoosnick** [comment]
@dantownsend Yes I know this command, if I have a project with 7-8 apps to create automatic migration files for all apps at one? We need such a command, which itself creates migration files in the directories related to the changes in the tables in each app.

Here's how I see it:
`piccolo migrations new all`
```
Creating migrations for 'myapp-1':
    Created tables                        2
    Dropped tables                        0
    Renamed tables                        0
    Created table columns                 5
    Dropped columns                       0
    Columns added to existing tables      0
    Renamed columns                       0
    Altered columns                       0
Creating migrations for 'myapp-2':
    Created tables                        2
    Dropped tables                        0
    Renamed tables                        0
    Created table columns                 5
    Dropped columns                       0
    Columns added to existing tables      0
    Renamed columns                       0
    Altered columns                       0
Creating migrations for 'myapp-3':
    Created tables                        2
    Dropped tables                        0
    Renamed tables                        0
    Created table columns                 5
    Dropped columns                       0
    Columns added to existing tables      0
    Renamed columns                       0
    Altered columns                       0
```
`piccolo migrations forwards all`
```
                          SESSION_AUTH
----------------------------------------------------------------
👍 1 migration already complete
🏁 No migrations need to be run

                              USER
----------------------------------------------------------------
👍 3 migrations already complete
🏁 No migrations need to be run

                         PICCOLO_ADMIN
----------------------------------------------------------------
👍 0 migrations already complete
🏁 No migrations need to be run

                             myapp-1
----------------------------------------------------------------
👍 8 migrations already complete
⏩ 1 migration not yet run
🚀 Running 1 migration:
  - 2023-07-13T14:37:01:492084 [forwards]... running 2023-07-13T14:37:01:492084
ok! ✔️

                            myapp-2
----------------------------------------------------------------
👍 2 migrations already complete
⏩ 1 migration not yet run
🚀 Running 1 migration:
  - 2023-07-13T14:37:01:492084 [forwards]... running 2023-07-13T14:37:01:492084
ok! ✔️

                             myapp-3
----------------------------------------------------------------
👍 1 migration already complete
⏩ 1 migration not yet run
🚀 Running 1 migration:
  - 2023-07-13T14:37:01:492084 [forwards]... running 2023-07-13T14:37:01:492084
ok! ✔️
```

**Comment by dantownsend** [comment]
Ah, I see - sorry for the confusion.

We have the ability to run all migrations - this should work:

```
piccolo migrations forwards all
```

I just checked and it's not in the docs - we should mention it [here](https://piccolo-orm.readthedocs.io/en/latest/piccolo/migrations/running.html#forwards).

There's no option currently to make migrations for all apps. We do what you suggest and have something like:

```
piccolo migrations new all
```

**Comment by hoosnick** [comment]
When do you plan to add it? 

I think if the AppConfig list of apps is returned in the method below, it's enough to go through the for loop in the [new command function](https://github.com/piccolo-orm/piccolo/blob/97292ccc27c379e17e9e964100a9da804055430b/piccolo/apps/migrations/commands/new.py#L210) in the migrations app.

https://github.com/piccolo-orm/piccolo/blob/97292ccc27c379e17e9e964100a9da804055430b/piccolo/conf/apps.py#L460-L469

https://github.com/piccolo-orm/piccolo/blob/97292ccc27c379e17e9e964100a9da804055430b/piccolo/apps/migrations/commands/new.py#L210-L249
