### ISSUE TITLE
`Ruff` as a linter for Piccolo

### ISSUE THREAD

**Issue by sinisaos** [piccolo-orm/piccolo#878]
Can we consider using [Ruff](https://beta.ruff.rs/docs/) as a linter for Piccolo? More and more projects are using Ruff as a much faster alternative to `Flake8`. If you want, I can do a PR for it, so if everything goes well (I tried it locally and everything works great), we can do the same for Piccolo API and Piccolo Admin?

**Comment by dantownsend** [comment]
Yeah, I've seen that is has become very popular.

My understanding is it's a replacement for flake8. I've never really had issues with the performance of flake8 - even though Piccolo is a pretty big project, I think the performance difference is probably more apparent when there's 100,000's or millions of lines of code.

**Comment by dantownsend** [comment]
I'm not sure if it gives a better developer experience in VSCode. I know VSCode is power hungry on my laptop, partially do to the all of the linters etc being run.

**Comment by sinisaos** [comment]
I don't know about VS Code, I ran it from the terminal with `./scripts/lint.sh` and Ruff executes in no time. Ruff also found a couple of `E721 Do not compare types, use isinstance()` like here https://github.com/piccolo-orm/piccolo/blob/83ea66323ef5a8e4010ea3ee19f34163bc881ace/piccolo/query/mixins.py#L114C9-L114C39
which should be `if not isinstance(self.interval, str):`, but we can fix it without Ruff. 
This was just an idea and if you think there won't be any special benefits, I'll close this issue.
