### ISSUE TITLE
Using piccolo on legacy data

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo#88]
Is there a way to have piccolo work on legacy database schemas (like managed = False in django)

**Comment by dantownsend** [comment]
@cheesycod There should be no problems with this - just define the models in Piccolo, and it can connect to existing database tables.

If using Piccolo migrations, the first time you run them you might want to use the fake flag.

```
piccolo migrations forwards some_app --fake
```

**Comment by vctrd** [comment]
Hello,

following up on this question, would an inspection mechanism such as `python manage.y inspectdb` to create the models in Piccolo automaticaly make sense ?

Thank you

**Comment by dantownsend** [comment]
Hi @vctrd, that's a good idea.

I've started putting together a simple prototype - will try and release this soon, as I can see it being a big time saver for people.

https://github.com/piccolo-orm/piccolo/pull/157

**Comment by vctrd** [comment]
Thank you very much, I'll have a look.
