### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by cheesycod** [piccolo-orm/piccolo#89]
Postgres supports arrays like bigint array, integer array etc. It would be nice to have support for these perhaps similar to how Django does it with a base_field

**Comment by dantownsend** [comment]
I've added Array support - you can get it on PyPI now.

**Comment by sinisaos** [comment]
@dantownsend I try a new Array column and add it to an existing table like this `tags = Array(base_column=Varchar())`.
When I run `piccolo migrations new blog --auto` I get this error 
```
Running Postgres version 10.16
Creating new migration ...
The command failed.
`_name` isn't defined - the Table Metaclass should set it.
```
Migrations with other columns work well. Am I doing something wrong or?

**Comment by dantownsend** [comment]
@sinisaos I'll give it a go locally - this could be a bug.

**Comment by dantownsend** [comment]
@sinisaos You're right, there was a bug with migrations when using the `Array` column type. I've pushed a new version to PyPI which should fix it. Can you give it another go when you have time? Thanks!

**Comment by sinisaos** [comment]
@dantownsend No problem. I will post the results here when I try out the new version later tonight.

**Comment by sinisaos** [comment]
@dantownsend `Array(base_column=Varchar())` now works perfectly. But for `Array(base_column=Integer())` I get this error
```
Running Postgres version 10.16
Creating new migration ...
The command failed.
__hash__ method should return an integer
```

**Comment by dantownsend** [comment]
@sinisaos Should be an easy fix - I'll investigate. Array columns are surprisingly tricky!

**Comment by sinisaos** [comment]
@dantownsend But it is useful for filtering in admin or for example tags without M2M fields FK fields. And the Array widget in admin looks great.

**Comment by dantownsend** [comment]
@sinisaos Thanks, I do think it's useful - like you say, for tags in particular. I've pushed a new version to PyPI - hopefully it fixes the Integer Array issue.

**Comment by sinisaos** [comment]
@dantownsend Now everything works great. Thanks
