### ISSUE TITLE
Implement support for Pydantic v2

### ISSUE THREAD

**Issue by aabmets** [piccolo-orm/piccolo#891]
This issue should be priority number 1. Pydantic v2 is already on v2.4.

**Comment by dantownsend** [comment]
Bear with me - it won't be much longer

**Comment by dantownsend** [comment]
It's available now: https://pypi.org/project/piccolo/1.0.0/

Just be aware that if you use `piccolo_admin`, you'll also want to upgrade that to the latest version too. https://pypi.org/project/piccolo-admin/1.0.0/

I don't anticipate any major issues upgrading to v1. I've already upgraded one of my main apps, and it seems OK so far. Let me know if you encounter any issues.
