### ISSUE TITLE
Mixins not working as it should

### ISSUE THREAD

**Issue by brnosouza** [piccolo-orm/piccolo#93]
Hello,

I'm trying to use Piccolo to one of my project, amazing work by the way, and I may have found a bug. I didn't figure this out yet, but I'll post here If I find something. 
I trying to implement the mixin pattern that I saw in the docs, however, when I execute any query, the collumns shows the name of the last class I included it, something like:

```python
class TimestampMixin:
    created_at = columns.Timestamp()
    updated_at = columns.Timestamp()

class Class1(TimestampMixin, Table, tablename='class_1'):
   # other columns

class Class2(TimestampMixin, Table, tablename='class_2'):
   # other columns
```

When I run a query for Class1, let's say a count query, this is what I get:

```python
str(Class1.count())

# 'SELECT COUNT(*) AS "count" FROM (SELECT class_1.id, class_2.created_at, class_2.updated_at FROM class_1) AS "subquery"'
```

So as we can see the `created_at` and `updated_at` are using a reference from the last class. Do you know if I'm doing something wrong here? The workaround for this right now is manually copying the fields and ignoring the mixin

**Comment by brnosouza** [comment]
I think I found the issue, the problem lies in the Table.__init_subclass__ (I think is line 168), the column is not being copied, piccolo is only adding it as a reference, which means this part:
```python
# ...
        for attribute_name in unique_attribute_names:
            if attribute_name.startswith("_"):
                continue

            attribute = getattr(cls, attribute_name)
            if isinstance(attribute, Column):
                column = attribute

                if isinstance(column, PrimaryKey):
                    # We want it at the start.
                    columns = [column] + columns  # type: ignore
                    default_columns.append(column)
                else:
                    columns.append(column)
                    non_default_columns.append(column)
# ...
```

should be:

```python
# ...
        for attribute_name in unique_attribute_names:
            if attribute_name.startswith("_"):
                continue

            attribute = getattr(cls, attribute_name)
            if isinstance(attribute, Column):
                column = attribute.copy()

                if isinstance(column, PrimaryKey):
                    # We want it at the start.
                    columns = [column] + columns  # type: ignore
                    default_columns.append(column)
                else:
                    columns.append(column)
                    non_default_columns.append(column)
# ...
```
I tinkered a bit and just adding the copy to attribute fixed the issue.

**Comment by dantownsend** [comment]
@brnosouza Thanks for reporting this, and working out the solution. 👍 

I'm just writing some unit tests to double check there are no side effects, and then I'll push the fix.

**Comment by brnosouza** [comment]
> @brnosouza Thanks for reporting this, and working out the solution. 
> 
> I'm just writing some unit tests to double check there are no side effects, and then I'll push the fix.

Awesome, thanks a lot for this :)

**Comment by brnosouza** [comment]
@dantownsend the fix worked perfectly, I'll close the ticket :smiley:
