### ISSUE TITLE
Pessimistic locking:  select for update

### ISSUE THREAD

**Issue by Abdelhadi92** [piccolo-orm/piccolo#932]
I need to lock an object in the database in order to prevent other transactions from modifying the same record. Within the Postgres such a lock should be done using the SELECT FOR UPDATE query.

How I can do this using Piccolo?

you can find it out in Django [here](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#select-for-update) and in Pony [here](https://docs.ponyorm.org/transactions.html#pessimistic-locking)

**Comment by dantownsend** [comment]
It's not currently possible, but I think it would be pretty simple to add.

We could add something like a `lock_strength` argument to the `select` method.

https://www.postgresql.org/docs/current/sql-select.html#SQL-FOR-UPDATE-SHARE

```python
await MyTable.select(lock_strength='UPDATE')
```

I'm not certain on the best API for it yet, but something like that should work.

**Comment by deliro** [comment]
I guess this one is an absolute must have. Any updates on it?

**Comment by dantownsend** [comment]
Implemented by https://github.com/piccolo-orm/piccolo/pull/1085
