### ISSUE TITLE
Are bit types supported?

### ISSUE THREAD

**Issue by waldner** [piccolo-orm/piccolo#985]
Postgres has two data types for storing bitstrings, `bit` and `bit varying` (see official docs https://www.postgresql.org/docs/current/datatype-bit.html). However, I don't see these documented for piccolo. Are they supported?

**Comment by dantownsend** [comment]
It's not supported at the moment.

You might be able to create your own custom column type:

https://piccolo-orm.readthedocs.io/en/latest/piccolo/schema/advanced.html#how-to-create-custom-column-types

It looks like asyncpg uses its own `asyncpg.BitString` type to represent the values:

https://magicstack.github.io/asyncpg/current/usage.html#type-conversion

**Comment by waldner** [comment]
I'll check the instructions out, thanks.
