### ISSUE TITLE
Pressing Enter in `Reverse 1 migration? [y/N]` still leads to reversing.

### ISSUE THREAD

**Issue by metakot** [piccolo-orm/piccolo#991]
When undoing the migration, pressing `Enter` after the prompt `Reverse 1 migration? [y/N]` still undoing it regardless of the default `N` behavior.

**Comment by dantownsend** [comment]
Ah, weird. I just tried it and I can see what you mean.

<img width="389" alt="Screenshot 2024-05-21 at 10 58 38" src="https://github.com/piccolo-orm/piccolo/assets/350976/ce7f7751-d893-402d-8c7d-54e63b0a6250">

I'll have a look at the code.

**Comment by dantownsend** [comment]
I've figured out the problem. Basically this is

```python
>>> '' in 'yY'
True
```

I think this is quite unintuitive - I would have expected `False`.
